name: Boilerplate Prod CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy_prod:
    name: build ande deploy to production
    uses: ./.github/workflows/cd-template.yml
    with:
      ENV_NAME: production