using System.Collections.Concurrent;

namespace Bit.BlazorUI;

/// <summary>
/// First-paint helpers for the accent color the <see cref="BitAccentColorSwitcher"/> applies, so a
/// server-rendered (and possibly CDN-cached) page paints the visitor's accent before hydration
/// instead of flashing the packaged palette first.
/// </summary>
/// <remarks>
/// <para>
/// The cookie half (<see cref="BuildRootAccentAttributes"/>, <see cref="BuildPrerenderCss"/>) covers
/// origin-rendered responses, where the server can read the visitor's preference. The client half
/// (<see cref="InlineHeadScript"/> plus, per <see cref="BitAccentColorFirstPaintStrategy"/>, a static stylesheet
/// from <see cref="BuildStaticCss"/> or the stored palette snapshot) covers everything the server
/// cannot: cached responses served to the wrong visitor, and stores newer than the cookie.
/// </para>
/// <para>
/// Attribute and storage names come from <see cref="BitAccentColorNames"/> so the inline script and
/// the runtime <c>BitBlazorUI.AccentColor</c> client stay in sync.
/// </para>
/// </remarks>
public static class BitAccentColorSsr
{
    /// <summary>
    /// The library version the accent CSS is generated by. Stamped into the localStorage palette
    /// snapshot the <see cref="BitAccentColorFirstPaintStrategy.StoredCss"/> strategy keeps - and compared by the
    /// inline head script before injecting it, because palette generation can change between
    /// releases and a snapshot written by another version must be ignored rather than painting
    /// yesterday's derivation. Also the natural cache-buster for a URL serving
    /// <see cref="BuildStaticCss"/>. The informational version rather than the assembly version,
    /// because the assembly version is not stamped per release (it stays 1.0.0.0); the '+' build
    /// metadata is trimmed so equal releases compare equal across rebuilds.
    /// </summary>
    public static readonly string Version = ResolveVersion();

    private static string ResolveVersion()
    {
        var informational = typeof(BitAccentColorSsr).Assembly
            .GetCustomAttributes(typeof(System.Reflection.AssemblyInformationalVersionAttribute), inherit: false)
            .OfType<System.Reflection.AssemblyInformationalVersionAttribute>()
            .FirstOrDefault()?.InformationalVersion;

        if (string.IsNullOrWhiteSpace(informational))
        {
            return typeof(BitAccentColorSsr).Assembly.GetName().Version?.ToString() ?? "0";
        }

        var metadataStart = informational.IndexOf('+', StringComparison.Ordinal);
        return metadataStart < 0 ? informational : informational[..metadataStart];
    }

    /// <summary>
    /// Rendered per-accent palette declarations, keyed by accent hex. Deriving a palette from a seed
    /// is real work (OKLCH conversions over ~280 tokens), and the same declarations feed the static
    /// stylesheet, the prerender style and the stored snapshot, so they are built once per accent.
    /// </summary>
    private static readonly ConcurrentDictionary<string, (string Dark, string Light)> _declarations = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>Rendered <see cref="BuildStaticCss"/> output, keyed by the joined accent tokens.</summary>
    private static readonly ConcurrentDictionary<string, string> _staticCss = new(StringComparer.Ordinal);

    /// <summary>Rendered <see cref="BuildSwatchMarkerCss"/> output, keyed by the joined accent tokens.</summary>
    private static readonly ConcurrentDictionary<string, string> _swatchMarkerCss = new(StringComparer.Ordinal);

    /// <summary>
    /// The number of distinct accent sets <see cref="_staticCss"/> and <see cref="_swatchMarkerCss"/>
    /// keep rendered output for. An app states its accents once, so a handful of sets covers every
    /// normal setup; the cap is what keeps a per-request or per-tenant accent list - or a switcher
    /// rendering with accents of its own - from pinning one full stylesheet per variation in a
    /// process-wide static, on Blazor Server for the lifetime of the process.
    /// </summary>
    private const int MaxCachedAccentSets = 32;

    /// <summary>
    /// <see cref="ConcurrentDictionary{TKey, TValue}.GetOrAdd(TKey, Func{TKey, TValue})"/> that stops
    /// adding past <see cref="MaxCachedAccentSets"/>: beyond the cap the output is rebuilt per call
    /// instead of cached - correct either way, and the repeating caller is by definition off the
    /// app-wide accent list this cache exists for.
    /// </summary>
    private static string GetOrBuild(ConcurrentDictionary<string, string> cache, string key, Func<string> build)
    {
        if (cache.TryGetValue(key, out var cached)) return cached;

        var built = build();

        if (cache.Count < MaxCachedAccentSets)
        {
            cache.TryAdd(key, built);
        }

        return built;
    }

    /// <summary>
    /// Rendered <see cref="BuildInlineHeadScriptBody"/> output, keyed by the persistence flags (only
    /// four combinations exist, so this stays tiny).
    /// </summary>
    private static readonly ConcurrentDictionary<BitAccentColorPersistence, string> _inlineScriptBodies = new();

    /// <summary>
    /// Inline script body without a wrapping <c>&lt;script&gt;</c> tag, reading both stores
    /// (<see cref="BitAccentColorPersistence.All"/>). Concatenate into your own
    /// <c>&lt;script&gt;</c> element when you need full control over attributes (CSP nonce,
    /// <c>type</c>, <c>defer</c>, etc.); use <see cref="BuildInlineHeadScriptBody"/> to restrict
    /// the stores the script reads.
    /// </summary>
    public static string InlineHeadScriptBody => BuildInlineHeadScriptBody(BitAccentColorPersistence.All);

    /// <summary>
    /// Full <c>&lt;script&gt;</c> markup ready to drop into <c>&lt;head&gt;</c>, before the
    /// stylesheets. It re-resolves the accent from localStorage / the preference cookie and, before
    /// anything is painted, sets the <c>bit-accent</c> attribute on the root element (which the
    /// <see cref="BuildStaticCss"/> stylesheet keys on) and injects the stored palette snapshot when
    /// one matches (the <see cref="BitAccentColorFirstPaintStrategy.StoredCss"/> strategy). Equivalent to
    /// <see cref="BuildInlineHeadScript"/> with a <see langword="null"/> nonce.
    /// </summary>
    public static string InlineHeadScript => BuildInlineHeadScript(nonce: null);

    /// <summary>
    /// Builds the inline first-paint script body, reading only the stores
    /// <paramref name="persistence"/> enables (the snapshot lives in localStorage, so its injection
    /// follows that flag too). Returns an empty string for
    /// <see cref="BitAccentColorPersistence.None"/> - with nothing persisted there is nothing for
    /// the script to do.
    /// </summary>
    public static string BuildInlineHeadScriptBody(BitAccentColorPersistence persistence = BitAccentColorPersistence.All)
    {
        return _inlineScriptBodies.GetOrAdd(persistence, BuildInlineScriptBody);
    }

    /// <summary>
    /// Builds the inline first-paint script wrapped in a <c>&lt;script&gt;</c> element, reading
    /// only the stores <paramref name="persistence"/> enables. Returns an empty string for
    /// <see cref="BitAccentColorPersistence.None"/>, so nothing is emitted when nothing is persisted.
    /// </summary>
    /// <param name="nonce">Optional CSP nonce. When supplied, the value is HTML-attribute-encoded and emitted as <c>nonce="…"</c>.</param>
    /// <param name="persistence">The stores the script reads the persisted accent from.</param>
    public static string BuildInlineHeadScript(string? nonce = null, BitAccentColorPersistence persistence = BitAccentColorPersistence.All)
    {
        var body = BuildInlineHeadScriptBody(persistence);

        return body.Length is 0 ? string.Empty : WrapScript(body, nonce);
    }

    /// <summary>
    /// Script body without a wrapping <c>&lt;script&gt;</c> tag that drops the server-emitted
    /// <see cref="BuildPrerenderCss"/> style when it does not carry the accent the inline head
    /// script resolved from the visitor's own stores. Emit it right after that style (see
    /// <see cref="BuildPrerenderCssGuardScript"/> for what it is for); concatenate it into your own
    /// <c>&lt;script&gt;</c> element when you need full control over the attributes.
    /// </summary>
    public static string PrerenderCssGuardScript => BuildPrerenderCssGuardScript(nonce: null);

    /// <summary>
    /// The guard of the <see cref="BitAccentColorFirstPaintStrategy.StoredCss"/> strategy, as a
    /// <c>&lt;script&gt;</c> element to emit immediately after the <see cref="BuildPrerenderCss"/>
    /// style: it removes that style unless the accent it was built for is the one the inline head
    /// script resolved from the visitor's own stores.
    /// </summary>
    /// <param name="nonce">Optional CSP nonce. When supplied, the value is HTML-attribute-encoded and emitted as <c>nonce="…"</c>.</param>
    /// <remarks>
    /// <para>
    /// The inline head script cannot do this itself: it runs before the style is parsed, so all it
    /// can reach is the <c>bit-accent</c> attribute - which the per-request style, carrying a single
    /// accent, does not key on. Without the guard a cached response keeps painting the accent of
    /// whichever visitor the origin rendered it for, right through to hydration.
    /// </para>
    /// <para>
    /// It also settles the case where both styles are present: the snapshot the inline head script
    /// injects lands earlier in <c>&lt;head&gt;</c> than the server's style, so at equal specificity
    /// a cookie that lags behind localStorage would otherwise win the first paint.
    /// </para>
    /// </remarks>
    public static string BuildPrerenderCssGuardScript(string? nonce = null)
    {
        // Only the server-emitted style carries the marker attribute, so the snapshot injected by the
        // inline head script - which is by definition the accent that script just resolved - is left
        // alone. A root element with no accent at all (nothing persisted) matches no marker either,
        // which is exactly the cached-response case this exists for.
        var body =
            $"(function(){{var t=document.documentElement.getAttribute('{BitAccentColorNames.Attribute}')," +
            $"l=document.querySelectorAll('style[id=\"{BitAccentColorNames.StyleElementId}\"][{BitAccentColorNames.StyleAccentAttribute}]');" +
            $"for(var i=0;i<l.length;i++){{if(l[i].getAttribute('{BitAccentColorNames.StyleAccentAttribute}')!==t)l[i].remove();}}}})();";

        return WrapScript(body, nonce);
    }

    private static string WrapScript(string body, string? nonce)
    {
        if (string.IsNullOrWhiteSpace(nonce))
        {
            return $"<script>{body}</script>";
        }

        // HTML-attribute-encode the nonce so a tampered value cannot break out of the attribute.
        // CSP nonces are base64url in practice, but defense-in-depth is cheap.
        var safeNonce = BitThemeSsr.HtmlEncodeAttribute(nonce);
        return $"<script nonce=\"{safeNonce}\">{body}</script>";
    }

    /// <summary>
    /// Builds the <c>bit-accent</c> attribute string to render on the root <c>&lt;html&gt;</c>
    /// element from the persisted preference (typically read from the
    /// <see cref="BitAccentColorNames.CookieName"/> cookie), so origin-rendered markup matches the
    /// <see cref="BuildStaticCss"/> stylesheet before the inline head script even runs.
    /// </summary>
    /// <param name="persistedAccent">
    /// The stored accent token - the accent hex with or without the leading <c>#</c>. Usually the
    /// cookie value; may be <see langword="null"/>/blank when no preference has been stored yet.
    /// </param>
    /// <returns>
    /// An attribute fragment such as <c>bit-accent="8764b8"</c>, or an empty string when nothing
    /// valid is persisted.
    /// </returns>
    /// <remarks>
    /// The value is normalized (trim, strip <c>#</c>, lower-case) and validated as a 3- or 6-digit
    /// hex token; anything else is ignored and treated as missing, so a tampered cookie cannot
    /// inject markup into the document. A token that matches none of the offered accents simply
    /// matches no stylesheet rule, which is harmless.
    /// </remarks>
    public static string BuildRootAccentAttributes(string? persistedAccent)
    {
        var token = NormalizeToken(persistedAccent);

        return token is null ? string.Empty : $"{BitAccentColorNames.Attribute}=\"{token}\"";
    }

    /// <summary>
    /// <see cref="BuildRootAccentAttributes"/> as an attribute map, for splatting onto the root
    /// element of a Razor host page - typically merged with
    /// <see cref="BitThemeSsr.BuildRootThemeAttributeMap"/>'s result into a single
    /// <c>@attributes</c> dictionary.
    /// </summary>
    public static IReadOnlyDictionary<string, object> BuildRootAccentAttributeMap(string? persistedAccent)
    {
        var token = NormalizeToken(persistedAccent);

        return token is null
            ? new Dictionary<string, object>(capacity: 0, StringComparer.Ordinal)
            : new Dictionary<string, object>(capacity: 1, StringComparer.Ordinal) { [BitAccentColorNames.Attribute] = token };
    }

    /// <summary>
    /// The accent-agnostic stylesheet of the <see cref="BitAccentColorFirstPaintStrategy.StaticCss"/> strategy: the
    /// full palette of every offered accent, each scoped to its own
    /// <c>bit-accent</c> attribute value and split dark/light on the <c>bit-theme</c> attribute.
    /// Because it is the same for every visitor, it can be served as a long-cached static asset (or
    /// emitted once into <c>&lt;head&gt;</c>) - which is exactly what makes this strategy safe behind a
    /// CDN cache.
    /// </summary>
    /// <param name="accents">
    /// The accents to include; <see langword="null"/> uses
    /// <see cref="BitAccentColorSwitcher.DefaultAccents"/>. An accent whose color is the packaged
    /// palette's own primary (<see cref="BitAccentColorPresets.Blue"/>) needs no override and is
    /// skipped, as is an accent whose color is not hex at all.
    /// </param>
    /// <remarks>
    /// <para>
    /// The doubled <c>:root:root</c> is there for specificity, not for matching: the packaged
    /// palette declares the same tokens at <c>:root[bit-theme=…]</c>, so an equal-specificity rule
    /// would only win by coming later in the document. Outranking it instead keeps the stylesheet
    /// order-independent.
    /// </para>
    /// <para>
    /// The rendered stylesheet is cached for the process lifetime, one entry per distinct accent
    /// token set, up to a fixed number of sets (past it the stylesheet is rendered per call). Reuse
    /// one fixed accent list (hoist it to a static or a singleton) rather than building a list per
    /// request or per tenant - every distinct set pins another full stylesheet in that cache, and
    /// enough of them turn every call into a full re-render.
    /// </para>
    /// </remarks>
    public static string BuildStaticCss(IEnumerable<BitAccentColorItem>? accents = null)
    {
        var items = (accents ?? BitAccentColorSwitcher.DefaultAccents)
                    .Select(a => (Token: NormalizeToken(a.Color), Hex: a.Color))
                    .Where(a => a.Token is not null && a.Token != NormalizeToken(BitAccentColorPresets.Blue))
                    .DistinctBy(a => a.Token)
                    .ToArray();

        var cacheKey = string.Join(',', items.Select(a => a.Token));

        return GetOrBuild(_staticCss, cacheKey, () =>
        {
            var builder = new System.Text.StringBuilder();
            foreach (var (token, hex) in items)
            {
                var (dark, light) = GetDeclarations(hex!);
                builder.Append($":root:root[{BitAccentColorNames.Attribute}=\"{token}\"][{BitThemeAttributeNames.Theme}$=dark]{{{dark}}}");
                builder.Append($":root:root[{BitAccentColorNames.Attribute}=\"{token}\"]:not([{BitThemeAttributeNames.Theme}$=dark]){{{light}}}");
            }
            return builder.ToString();
        });
    }

    /// <summary>
    /// The pre-paint active-swatch marker the CSS strategies need: one rule ringing the
    /// <see cref="BitAccentColorSwitcher"/> swatch whose token the <c>bit-accent</c> root attribute
    /// carries (plus the packaged primary's swatch when no attribute is set, i.e. "no override"), so
    /// prerendered and cached markup rings the visitor's swatch immediately instead of ringing the
    /// default until hydration. Accent-agnostic like <see cref="BuildStaticCss"/>, so it is safe in a
    /// cached response.
    /// </summary>
    /// <param name="accents">
    /// The accents to mark; <see langword="null"/> uses
    /// <see cref="BitAccentColorSwitcher.DefaultAccents"/>. An accent whose color is not hex is
    /// skipped - it is not a swatch the switcher can paint either.
    /// </param>
    /// <remarks>
    /// <para>
    /// Emitted by <see cref="BitAccentColorHead"/> alongside the palette CSS rather than by the
    /// switcher itself, because this is first-paint machinery like the rest of it: emitting it from
    /// the host page's <c>&lt;head&gt;</c> costs one style element per response instead of one per
    /// switcher instance, and - the reason it cannot stay in the component - it is the only place a
    /// CSP nonce exists. A style element a switcher renders has no nonce to carry (the value is
    /// per-response, and an interactively-rendered switcher never sees it), so a
    /// <c>style-src 'nonce-…'</c> policy blocks it and no swatch is ever marked.
    /// </para>
    /// <para>
    /// The rules deliberately do not scope to a switcher instance: a swatch is ringed exactly when
    /// its own token is the active accent, which holds for every instance offering that accent. A
    /// switcher configured with accents of its own (rather than the app-wide list this is built
    /// from) is simply not covered pre-paint; its ring arrives with hydration, from the C# state.
    /// The declarations mirror <c>.bit-acs-act</c> in <c>BitAccentColorSwitcher.scss</c>.
    /// </para>
    /// </remarks>
    public static string BuildSwatchMarkerCss(IEnumerable<BitAccentColorItem>? accents = null)
    {
        var tokens = (accents ?? BitAccentColorSwitcher.DefaultAccents)
                     .Select(a => NormalizeToken(a.Color))
                     .Where(t => t is not null)
                     .Distinct(StringComparer.Ordinal)
                     .ToArray();

        return GetOrBuild(_swatchMarkerCss, string.Join(',', tokens), () =>
        {
            var neutral = NormalizeToken(BitAccentColorPresets.Blue);
            var selectors = new List<string>();

            foreach (var token in tokens)
            {
                selectors.Add($":root[{BitAccentColorNames.Attribute}=\"{token}\"] [{BitAccentColorNames.SwatchAttribute}=\"{token}\"]");

                if (token == neutral)
                {
                    selectors.Add($":root:not([{BitAccentColorNames.Attribute}]) [{BitAccentColorNames.SwatchAttribute}=\"{token}\"]");
                }
            }

            return selectors.Count is 0
                ? string.Empty
                : $"{string.Join(',', selectors)}{{outline:0.125rem solid var(--bit-acs-clr);outline-offset:0.125rem;}}";
        });
    }

    /// <summary>
    /// The per-request style the server emits so an origin-rendered page paints the persisted accent
    /// immediately - the server half of the <see cref="BitAccentColorFirstPaintStrategy.StoredCss"/> strategy (in
    /// <see cref="BitAccentColorFirstPaintStrategy.StaticCss"/> strategy the static stylesheet plus
    /// <see cref="BuildRootAccentAttributes"/> covers this instead). Emit it into
    /// <c>&lt;head&gt;</c> as <c>&lt;style id="@BitAccentColorNames.StyleElementId"&gt;</c>, after
    /// the theme's inline head script (the rules are split on the <c>bit-theme</c> attribute that
    /// script sets). Returns <see langword="null"/> when there is nothing to override - no stored
    /// accent, an unrecognized one, or the packaged primary.
    /// </summary>
    /// <remarks>
    /// The style is per-visitor, so mark it with
    /// <c>@BitAccentColorNames.StyleAccentAttribute="&lt;token&gt;"</c> and emit
    /// <see cref="BuildPrerenderCssGuardScript"/> right after it - that pair is what stops a cached
    /// response from painting this accent for the next visitor. <see cref="BitAccentColorHead"/>
    /// does all of it; this is for hosts that emit the head half themselves.
    /// </remarks>
    /// <param name="persistedAccent">
    /// The stored accent token, usually the <see cref="BitAccentColorNames.CookieName"/> cookie value.
    /// </param>
    /// <param name="accents">
    /// The accents the value is validated against; <see langword="null"/> uses
    /// <see cref="BitAccentColorSwitcher.DefaultAccents"/>. The stores are visitor-editable, so only
    /// a recognized accent is ever handed to <see cref="BitThemeFactory"/> - a tampered value cannot
    /// trigger palette derivation for arbitrary input, nor grow the cache unboundedly.
    /// </param>
    public static string? BuildPrerenderCss(string? persistedAccent, IEnumerable<BitAccentColorItem>? accents = null)
    {
        var token = NormalizeToken(persistedAccent);
        if (token is null || token == NormalizeToken(BitAccentColorPresets.Blue)) return null;

        var match = (accents ?? BitAccentColorSwitcher.DefaultAccents).FirstOrDefault(a => NormalizeToken(a.Color) == token);
        if (match is null) return null;

        return BuildSnapshotCss(match.Color);
    }

    /// <summary>
    /// The accent-scoped-to-theme-only palette CSS shared by <see cref="BuildPrerenderCss"/> and the
    /// <see cref="BitAccentColorFirstPaintStrategy.StoredCss"/> snapshot: unlike the static stylesheet it carries a
    /// single accent, so it applies through the <c>bit-theme</c> split alone.
    /// </summary>
    internal static string BuildSnapshotCss(string accentHex)
    {
        var (dark, light) = GetDeclarations(accentHex);

        return $":root:root[{BitThemeAttributeNames.Theme}$=dark]{{{dark}}}" +
               $":root:root:not([{BitThemeAttributeNames.Theme}$=dark]){{{light}}}";
    }

    /// <summary>
    /// Normalizes an accent value (trim, strip a leading <c>#</c>, lower-case) into the canonical
    /// token used for the <c>bit-accent</c> attribute and both persistence stores, and validates it
    /// as a 3- or 6-digit hex. Returns <see langword="null"/> for blank or invalid input so callers
    /// treat it as "no preference" - this is also what keeps a tampered store value out of the
    /// document.
    /// </summary>
    internal static string? NormalizeToken(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;

        var token = value.Trim().TrimStart('#').ToLowerInvariant();
        if (token.Length is not (3 or 6)) return null;

        foreach (var ch in token)
        {
            if (ch is (< '0' or > '9') and (< 'a' or > 'f')) return null;
        }

        return token;
    }

    /// <summary>
    /// <see cref="NormalizeToken"/> as a color rather than a token: the canonical <c>#</c>-prefixed
    /// lower-case hex, or <see langword="null"/> for anything that is not hex at all. This is the
    /// shape <see cref="BitThemeFactory"/> and CSS both require, while the feature accepts a bare
    /// token wherever it accepts a color (that is what <see cref="NormalizeToken"/> validates), so
    /// every path that hands an accent to the factory or writes it into a declaration has to come
    /// through here - otherwise an <c>Accents</c> entry spelled <c>8764b8</c> works in one half of
    /// the feature and fails in the other.
    /// </summary>
    internal static string? CanonicalizeHex(string? value)
    {
        return NormalizeToken(value) is { } token ? $"#{token}" : null;
    }

    /// <summary>
    /// The cache stops growing past this many distinct accents. The offered accent lists this cache
    /// exists for are a handful of colors; only the programmatic <c>ApplyAsync</c> path can feed it
    /// arbitrary hexes (e.g. an app wiring a free-form color picker to it), and each entry pins two
    /// full palettes (~tens of KB) in a process-wide static for the process lifetime - on Blazor
    /// Server, shared across every circuit.
    /// </summary>
    private const int MaxCachedDeclarations = 64;

    private static (string Dark, string Light) GetDeclarations(string accentHex)
    {
        // The callers validate with NormalizeToken, which accepts a bare "8764b8" - the factory does
        // not, so canonicalizing here is what keeps such an accent from throwing while the host
        // page's <head> is being rendered. It also collapses every spelling of one accent onto a
        // single cache entry. A value that is not hex at all is passed through for the factory to
        // reject with its own message.
        var seed = CanonicalizeHex(accentHex) ?? accentHex;

        // The dark/light split matches the library's own [bit-theme$=dark] convention, so "fluent-dark"
        // and any other dark preset land on the dark palette too.
        if (_declarations.TryGetValue(seed, out var cached)) return cached;

        var derived = (Declarations(BitThemeFactory.CreateDarkThemeFromSeed(seed)), Declarations(BitThemeFactory.CreateLightThemeFromSeed(seed)));

        // Past the cap the derivation is repeated per call instead of cached: correct either way,
        // and the repeating caller is by definition off the offered lists.
        if (_declarations.Count < MaxCachedDeclarations)
        {
            _declarations.TryAdd(seed, derived);
        }

        return derived;

        static string Declarations(BitTheme theme)
        {
            return string.Concat(BitThemeUtilities.ToCssVariables(theme).Select(v => $"{v.Key}:{v.Value};"));
        }
    }

    private static string BuildInlineScriptBody(BitAccentColorPersistence persistence)
    {
        var readLocalStorage = persistence.HasFlag(BitAccentColorPersistence.LocalStorage);
        var readCookie = persistence.HasFlag(BitAccentColorPersistence.Cookie);

        // With nothing persisted there is nothing to restore pre-paint; no script at all beats a
        // script that does nothing on every load.
        if (readLocalStorage is false && readCookie is false) return string.Empty;

        // Centralizing names through BitAccentColorNames means the inline script picks up renames
        // automatically and cannot drift from the BitAccentColor.ts runtime client.
        var attribute = BitAccentColorNames.Attribute;
        var storageKey = BitAccentColorNames.StorageKey;
        var cookieName = BitAccentColorNames.CookieName;
        var cssStorageKey = BitAccentColorNames.CssStorageKey;
        var styleElementId = BitAccentColorNames.StyleElementId;

        // The inline script is intentionally compact; it runs on every first paint before stylesheets.
        // Only the stores the persistence flags enable are read (the snapshot lives in localStorage,
        // so it follows that flag). The token regex mirrors NormalizeToken, so a tampered store value
        // never reaches the document. The snapshot is only injected when it matches both the
        // persisted token and this library version (see Version), and lands through
        // textContent, which cannot break out into markup; the '<' scan on top of that is cheap
        // defense-in-depth.
        // The injected style element carries the nonce of the script element injecting it, read off
        // document.currentScript rather than baked in here - a nonce is per-response, so baking it
        // into this body would make the cache above grow by one full script per request. Browsers
        // hide the nonce content attribute, hence the IDL property first and getAttribute only as a
        // fallback for engines predating it.
        return
            "(function(){var r=document.documentElement," +
            $"k='{storageKey}'," +
            $"ck='{cookieName}'," +
            $"sk='{cssStorageKey}'," +
            "v=null;" +
            (readLocalStorage ? "try{v=localStorage.getItem(k);}catch(e){}" : string.Empty) +
            (readCookie ? "if(!v){var m=('; '+document.cookie).match('; '+ck+'=([^;]*)');if(m){try{v=decodeURIComponent(m[1]);}catch(e){v=m[1];}}}" : string.Empty) +
            // With nothing (valid) persisted, any bit-accent already on the root element is a
            // server-rendered attribute for some OTHER visitor's cookie, served to this one from a
            // cache - remove it, or the static stylesheet would paint their accent here.
            $"if(!v||!/^[0-9a-f]{{3}}([0-9a-f]{{3}})?$/.test(v)){{r.removeAttribute('{attribute}');return;}}" +
            $"r.setAttribute('{attribute}',v);" +
            (readLocalStorage
                ? "try{var s=localStorage.getItem(sk);if(s){var o=JSON.parse(s);" +
                  $"if(o&&o.a===v&&o.v==='{Version}'&&typeof o.css==='string'&&o.css.indexOf('<')<0){{" +
                  "var cs=document.currentScript,n=cs&&(cs.nonce||cs.getAttribute('nonce'));" +
                  $"var el=document.createElement('style');el.id='{styleElementId}';if(n)el.setAttribute('nonce',n);el.textContent=o.css;document.head.appendChild(el);}}}}}}catch(e){{}}"
                : string.Empty) +
            "})();";
    }
}
