using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Bit.Brouter.Generators;

/// <summary>
/// Generates <c>BrouterRoutes</c> - one compile-time-safe URL builder method per route declared in
/// the project's .razor files (<c>@page</c>, <c>@attribute [Route]</c> and literal
/// <c>&lt;Broute Path="..."&gt;</c> trees). Route parameters become typed method parameters using
/// the template's constraints (<c>{id:int}</c> → <c>int id</c>), optionals become optional
/// arguments, catch-alls become path strings, and values are escaped/formatted with the exact
/// rules the router itself uses - so a generated URL always round-trips through its template.
/// </summary>
[Generator]
public sealed class BrouterRoutesGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor _conflictingRouteNames = new(
        id: "BRT001",
        title: "Duplicate route template with conflicting names",
        messageFormat: "The route template \"/{0}\" is declared more than once with different names (\"{1}\" and \"{2}\"); only \"{1}\" gets a URL builder and Names constant",
        category: "Bit.Brouter.Generators",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var routesPerFile = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
            .Select(static (text, ct) =>
            {
                var content = text.GetText(ct)?.ToString() ?? string.Empty;
                return new EquatableArray<RouteModel>(RazorRouteScanner.Scan(content).ToArray());
            })
            .Where(static routes => routes.Count > 0)
            .Collect();

        var rootNamespace = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) =>
                provider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns) && string.IsNullOrWhiteSpace(ns) is false
                    ? ns
                    : "Bit.Brouter.Generated");

        context.RegisterSourceOutput(routesPerFile.Combine(rootNamespace), static (spc, input) =>
        {
            var (perFile, ns) = input;
            var source = Emit(perFile, ns, spc);
            if (source is not null)
            {
                spc.AddSource("BrouterRoutes.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static string? Emit(ImmutableArray<EquatableArray<RouteModel>> perFile, string ns, SourceProductionContext spc)
    {
        // Dedup by canonical template (case-insensitive; parameter names don't distinguish
        // templates at runtime, but for generation the first declaration's names/types win -
        // matching the router's "hand-declared shadows discovered" precedence closely enough).
        // A named declaration is preferred over an unnamed duplicate so Names constants survive.
        var byTemplate = new Dictionary<string, RouteModel>(StringComparer.OrdinalIgnoreCase);
        foreach (var file in perFile)
        {
            foreach (var route in file.Items)
            {
                if (byTemplate.TryGetValue(route.Template, out var existing))
                {
                    // Two different explicit names on the same template is a declaration bug the
                    // first-wins dedup would otherwise hide - surface it instead of guessing.
                    if (existing.Name is not null && route.Name is not null
                        && string.Equals(existing.Name, route.Name, StringComparison.Ordinal) is false)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(
                            _conflictingRouteNames, Location.None, route.Template, existing.Name, route.Name));
                    }
                    if (existing.Name is null && route.Name is not null) byTemplate[route.Template] = route;
                    continue;
                }
                byTemplate[route.Template] = route;
            }
        }

        if (byTemplate.Count == 0) return null;

        var routes = byTemplate.Values.OrderBy(r => r.Template, StringComparer.Ordinal).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Bit.Brouter.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Compile-time-safe URL builders for this app's Brouter routes.</summary>");
        sb.AppendLine("public static partial class BrouterRoutes");
        sb.AppendLine("{");

        // Method-name assignment happens in two passes so an explicitly named route always owns
        // its own name: "Name=counter" must yield Counter(...) even when an unnamed "/counter"
        // template would derive the same identifier (that one gets the numeric suffix instead).
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var methodNames = new Dictionary<RouteModel, string>();
        foreach (var route in routes)
        {
            if (route.Name is not null) methodNames[route] = MakeUnique(MethodNameFor(route), usedNames);
        }
        foreach (var route in routes)
        {
            if (route.Name is null) methodNames[route] = MakeUnique(MethodNameFor(route), usedNames);
        }

        var namedRoutes = new List<(string Constant, string Name)>();
        foreach (var route in routes)
        {
            var methodName = methodNames[route];
            if (route.Name is not null)
            {
                namedRoutes.Add((methodName, route.Name));
            }
            EmitMethod(sb, route, methodName);
        }

        if (namedRoutes.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>The declared route names, for NavigateToName/ResolveUrl without magic strings.</summary>");
            sb.AppendLine("    public static class Names");
            sb.AppendLine("    {");
            var usedConstants = new HashSet<string>(StringComparer.Ordinal);
            foreach (var (constant, name) in namedRoutes)
            {
                var constantName = MakeUnique(constant, usedConstants);
                sb.AppendLine($"        public const string {constantName} = \"{Escape(name)}\";");
            }
            sb.AppendLine("    }");
        }

        EmitHelpers(sb);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, RouteModel route, string methodName)
    {
        var parameters = new List<string>();
        var body = new StringBuilder();

        foreach (var segment in route.Segments.Items)
        {
            switch (segment.Kind)
            {
                case SegmentKind.Literal:
                    body.AppendLine($"        sb.Append(\"/{Escape(segment.Value)}\");");
                    break;

                case SegmentKind.Parameter:
                    var paramName = ParameterNameFor(segment.Value);
                    if (segment.IsOptional)
                    {
                        var optionalType = segment.ClrType == "string" ? "string?" : segment.ClrType + "?";
                        parameters.Add($"{optionalType} {paramName} = null");
                        // Trailing optionals: emit only while values are provided (the template
                        // parser guarantees optionals are trailing, so no literal follows).
                        body.AppendLine($"        if ({paramName} is not null) sb.Append('/').Append(global::System.Uri.EscapeDataString(__Format({paramName})));");
                    }
                    else
                    {
                        parameters.Add($"{segment.ClrType} {paramName}");
                        body.AppendLine($"        sb.Append('/').Append(global::System.Uri.EscapeDataString(__Format({paramName})));");
                    }
                    break;

                case SegmentKind.CatchAll:
                    var catchAllName = ParameterNameFor(segment.Value);
                    parameters.Add($"string? {catchAllName} = null");
                    body.AppendLine($"        if (!string.IsNullOrEmpty({catchAllName}))");
                    body.AppendLine("        {");
                    body.AppendLine($"            foreach (var __seg in {catchAllName}!.Split(new[] {{ '/' }}, global::System.StringSplitOptions.RemoveEmptyEntries))");
                    body.AppendLine("            {");
                    body.AppendLine("                sb.Append('/').Append(global::System.Uri.EscapeDataString(__seg));");
                    body.AppendLine("            }");
                    body.AppendLine("        }");
                    break;
            }
        }

        parameters.Add("string? query = null");

        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Builds a URL for the route template <c>\"/{Escape(route.Template)}\"</c>.</summary>");
        sb.AppendLine($"    public static string {methodName}({string.Join(", ", parameters)})");
        sb.AppendLine("    {");
        sb.AppendLine("        var sb = new global::System.Text.StringBuilder();");
        sb.Append(body);
        sb.AppendLine("        if (sb.Length == 0) sb.Append('/');");
        sb.AppendLine("        if (!string.IsNullOrEmpty(query)) sb.Append(query![0] == '?' ? query : \"?\" + query);");
        sb.AppendLine("        return sb.ToString();");
        sb.AppendLine("    }");
    }

    private static void EmitHelpers(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("    // Mirrors the router's invariant route-value formatting so generated URLs and");
        sb.AppendLine("    // ResolveUrl-produced URLs are byte-identical for the same values.");
        sb.AppendLine("    private static string __Format(object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value is null) return string.Empty;");
        sb.AppendLine("        if (value is string s) return s;");
        sb.AppendLine("        if (value is bool b) return b ? \"true\" : \"false\";");
        sb.AppendLine("        if (value is global::System.DateTime dt) return dt.ToString(\"o\", global::System.Globalization.CultureInfo.InvariantCulture);");
        sb.AppendLine("        if (value is global::System.IFormattable f) return f.ToString(null, global::System.Globalization.CultureInfo.InvariantCulture);");
        sb.AppendLine("        return value.ToString() ?? string.Empty;");
        sb.AppendLine("    }");
    }

    /// <summary>Derives the method name: the explicit route Name when present, else the template's literals (fallback: parameter names).</summary>
    private static string MethodNameFor(RouteModel route)
    {
        if (string.IsNullOrWhiteSpace(route.Name) is false)
        {
            return Pascalize(route.Name!);
        }

        var literals = new StringBuilder();
        foreach (var segment in route.Segments.Items)
        {
            if (segment.Kind == SegmentKind.Literal) literals.Append(Pascalize(segment.Value));
        }
        if (literals.Length > 0)
        {
            // "/users/{id}" and "/users" both start from "Users"; parameterized templates get a
            // "By{Param}" suffix so the pair reads naturally and rarely collides.
            foreach (var segment in route.Segments.Items)
            {
                if (segment.Kind == SegmentKind.Parameter) literals.Append("By").Append(Pascalize(segment.Value));
            }
            return literals.ToString();
        }

        if (route.Segments.Count == 0) return "Root";

        var fromParams = new StringBuilder("By");
        foreach (var segment in route.Segments.Items)
        {
            if (segment.Kind is SegmentKind.Parameter or SegmentKind.CatchAll) fromParams.Append(Pascalize(segment.Value));
        }
        return fromParams.Length > 2 ? fromParams.ToString() : "Route";
    }

    private static string Pascalize(string value)
    {
        var sb = new StringBuilder(value.Length);
        var upperNext = true;
        foreach (var c in value)
        {
            if (char.IsLetterOrDigit(c) is false)
            {
                upperNext = true;
                continue;
            }
            sb.Append(upperNext ? char.ToUpperInvariant(c) : c);
            upperNext = false;
        }
        if (sb.Length == 0) return "Route";
        if (char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }

    private static string ParameterNameFor(string templateParamName)
    {
        // Route parameter names are already identifier-shaped (the parser validated them);
        // lower-case the first letter for C# convention and keyword-proof with '@'.
        var name = char.ToLowerInvariant(templateParamName[0]) + templateParamName.Substring(1);
        return "@" + name;
    }

    private static string MakeUnique(string name, HashSet<string> used)
    {
        if (used.Add(name)) return name;
        for (var i = 2; ; i++)
        {
            var candidate = name + i.ToString(System.Globalization.CultureInfo.InvariantCulture);
            if (used.Add(candidate)) return candidate;
        }
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
