name: AdminPanel CI

# https://bitplatform.dev/admin-panel/dev-ops

env:
  WEB_APP_DEPLOYMENT_TYPE: 'Spa'

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:

  build-blazor-server:
    name: build blazor server
    runs-on: ubuntu-22.04

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - uses: actions/setup-node@v3
      with:
        node-version: 18
      
    - name: Build
      run: dotnet build src/Client/Web/AdminPanel.Client.Web.csproj -p:Configuration=Release -p:WebAppDeploymentType="${{ env.WEB_APP_DEPLOYMENT_TYPE }}"

  build-blazor-hybrid-android:
    name: build blazor hybrid (android)
    runs-on: windows-2022

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Maui
      run: dotnet workload install maui

    - name: Restore workloads
      run: dotnet workload restore src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -f net7.0-android

    - name: Build
      run: dotnet build src/Client/App/AdminPanel.Client.App.csproj -p:RunAOTCompilation=false -p:BlazorMode=BlazorHybrid -p:Configuration=Release -f net7.0-android

  build-blazor-hybrid-windows:
    name: build blazor hybrid (windows)
    runs-on: windows-2022

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Maui
      run: dotnet workload install maui

    - name: Restore workloads
      run: dotnet workload restore src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -f net7.0-windows10.0.19041.0

    - name: Build
      run: dotnet build src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -f net7.0-windows10.0.19041.0

  build-blazor-hybrid-iOS:
    name: build blazor hybrid (iOS)
    runs-on: macos-12

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Maui
      run: dotnet workload install maui

    - name: Restore workloads
      run: dotnet workload restore src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -f net7.0-ios

    - name: Build
      run: dotnet build src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -f net7.0-ios

  build-blazor-hybrid-maccatalyst:
    name: build blazor hybrid (maccatalyst)
    runs-on: macos-12

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Maui
      run: dotnet workload install maui

    - name: Restore workloads
      run: dotnet workload restore src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -f net7.0-maccatalyst
      
    - name: Build
      run: dotnet build src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -f net7.0-maccatalyst

  build-blazor-api-wasm:
    name: build blazor api + web assembly
    runs-on: ubuntu-22.04

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Switch to blazor wasm
      run:  sed -i 's/Microsoft.NET.Sdk.Web/Microsoft.NET.Sdk.BlazorWebAssembly/g' src/Client/Web/AdminPanel.Client.Web.csproj

    - name: Restore workloads
      run: dotnet workload restore src/Client/Web/AdminPanel.Client.Web.csproj -p:BlazorMode=BlazorWebAssembly
      
    - name: Build
      run: dotnet build src/Server/Api/AdminPanel.Server.Api.csproj -p:BlazorMode=BlazorWebAssembly -p:Configuration=Release -p:WebAppDeploymentType="${{ env.WEB_APP_DEPLOYMENT_TYPE }}"