using Newtonsoft.Json;

namespace Bit.BlazorUI.Legacy;

/// <summary>
/// As per documentation <a href="https://www.chartjs.org/docs/latest/axes/cartesian/#common-configuration">here (Chart.js)</a>.
/// </summary>
public abstract class BitChartLegacyCartesianAxis : BitChartLegacyAxis
{
    /// <summary>
    /// The type of axis this instance represents.
    /// <para>For js-interop/serialization purposes so Chart.js knows what axis to use.</para>
    /// </summary>
    public abstract BitChartLegacyAxisType Type { get; }

    /// <summary>
    /// The ID is used to link <see cref="BitChartLegacyLineDataset{T}"/>/<see cref="BitChartLegacyBarDataset{T}"/> and <see cref="BitChartLegacyCartesianAxis"/> together.
    /// Referenced in <see cref="BitChartLegacyLineDataset{T}.XAxisId"/> and <seealso cref="BitChartLegacyLineDataset{T}.YAxisId"/>
    /// (<see cref="BitChartLegacyBarDataset{T}.XAxisId"/> and <seealso cref="BitChartLegacyBarDataset{T}.YAxisId"/> respectively).
    /// </summary>
    [JsonProperty("id")]
    public string? ID { get; set; }

    /// <summary>
    /// Gets or sets the position of the axis in the chart.
    /// </summary>
    public BitChartLegacyPosition? Position { get; set; }

    /// <summary>
    /// If true, extra space is added to the both edges and the axis is scaled to fit into the chart area.
    /// This is set to true for a category scale in a bar chart by default.
    /// </summary>
    public bool? Offset { get; set; }

    /// <summary>
    /// Gets or sets the scale title configuration.
    /// </summary>
    public BitChartLegacyScaleLabel? ScaleLabel { get; set; }

    /// <summary>
    /// Defines options for the grid lines that run perpendicular to the axis.
    /// </summary>
    public BitChartLegacyGridLines? GridLines { get; set; }
}

/// <summary>
/// <see cref="BitChartLegacyCartesianAxis"/> which contains the ticks-subconfig.
/// </summary>
/// <typeparam name="TTicks"></typeparam>
public abstract class BitChartLegacyCartesianAxis<TTicks> : BitChartLegacyCartesianAxis where TTicks : BitChartLegacyCartesianTicks
{
    /// <summary>
    /// Defines options for the tick marks that are generated by the axis.
    /// </summary>
    public TTicks? Ticks { get; set; }
}
