// <auto-generated />
using Bit.Besql.Demo.Client.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bit.Besql.Demo.Client.Data.Migrations
{
    [DbContext(typeof(OfflineDbContext))]
    partial class OfflineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Bit.Besql.Demo.Client.Model.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemperatureC");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = 1307437068492800000L,
                            Summary = "Hot",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 2,
                            Date = 1307438837964800000L,
                            Summary = "Normal",
                            TemperatureC = 20
                        },
                        new
                        {
                            Id = 3,
                            Date = 1307440607436800000L,
                            Summary = "Cold",
                            TemperatureC = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
