"""
Generates the country flag image sets of Bit.BlazorUI.Assets, and the boxes BitFlag cuts a shaped frame
to, out of one folder of source png images.

    python -m pip install pillow
    python Bit.BlazorUI.Assets/Scripts/generate-flags.py <source folder>

The source folder holds one folder per ISO 3166-1 alpha-2 code, each carrying the ten images
flat-16.png ... flat-64.png and shiny-16.png ... shiny-64.png. A folder missing any of them is skipped,
and the codes left have to be exactly the ones the packaged 16 pixel images of Bit.BlazorUI.Extras
cover - which are the countries of BitCountries.All - or nothing is written.

What it writes:

  - Bit.BlazorUI.Assets/wwwroot/flags/<ISO2>-<set>-<size>.webp, replacing whatever was there. The flat
    set is lossless: its artwork is flat color, where lossless WebP is both smaller and exact. The shiny
    set is lossy at quality 90 with a lossless alpha channel: its gradients are what lossy WebP is for,
    at about half the size of lossless.
  - Bit.BlazorUI.Extras/Components/Flag/BitFlag.razor.boxes.cs, the box every image draws its flag in.
"""

import argparse
import os
import sys
from collections import Counter

from PIL import Image

SETS = ("flat", "shiny")
SIZES = (16, 24, 32, 48, 64)

# A pixel counts as part of the flag once it is at least half opaque, so the faint edge the artwork
# antialiases a flag with is left outside the box rather than rounded, bordered and shadowed.
OPAQUE = 128

HERE = os.path.dirname(os.path.abspath(__file__))
BLAZORUI = os.path.normpath(os.path.join(HERE, "..", ".."))
ASSETS_FLAGS = os.path.join(BLAZORUI, "Bit.BlazorUI.Assets", "wwwroot", "flags")
EXTRAS_FLAGS = os.path.join(BLAZORUI, "Bit.BlazorUI.Extras", "wwwroot", "flags")
BOXES_FILE = os.path.join(BLAZORUI, "Bit.BlazorUI.Extras", "Components", "Flag", "BitFlag.razor.boxes.cs")
EXTRAS_SUFFIX = "-flat-16.webp"


def source_codes(source):
    codes, skipped = [], []
    for code in sorted(os.listdir(source)):
        folder = os.path.join(source, code)
        if os.path.isdir(folder) is False:
            continue
        if all(os.path.isfile(os.path.join(folder, f"{s}-{z}.png")) for s in SETS for z in SIZES):
            codes.append(code.upper())
        else:
            skipped.append(code)
    return codes, skipped


def content_box(image):
    mask = image.getchannel("A").point(lambda a: 255 if a >= OPAQUE else 0)
    left, top, right, bottom = mask.getbbox()
    return (left, top, right - left, bottom - top)


def encode(image, set_name, path):
    if set_name == "flat":
        image.save(path, "WEBP", lossless=True, quality=100, method=6, exact=True)
    else:
        image.save(path, "WEBP", quality=90, alpha_quality=100, method=6)

    # The flat set has to come back exactly as it went in, and the shiny set with the alpha channel the
    # boxes are measured on: a box that no longer matches the pixels drawn would cut the flag wrong.
    with Image.open(path) as written:
        written = written.convert("RGBA")
        if set_name == "flat":
            if written.tobytes() != image.tobytes():
                sys.exit(f"{path} did not round-trip losslessly")
        elif content_box(written) != content_box(image):
            sys.exit(f"{path} does not keep the content box of its source")


def write_boxes(boxes):
    lines = [
        "// <auto-generated>",
        "// GENERATED by Bit.BlazorUI.Assets/Scripts/generate-flags.py, together with the flag images of",
        "// Bit.BlazorUI.Assets/wwwroot/flags. Regenerate with that script, never by hand.",
        "// </auto-generated>",
        "",
        "#nullable enable",
        "",
        "namespace Bit.BlazorUI;",
        "",
        "public partial class BitFlag",
        "{",
        "    /// <summary>",
        "    /// The pixel sizes every image set of the Bit.BlazorUI.Assets package draws each flag at, smallest first.",
        "    /// </summary>",
        f"    private static readonly int[] FlagImageSizes = [{', '.join(str(z) for z in SIZES)}];",
        "",
        "    /// <summary>",
        "    /// The box a flag image draws its flag in, in the pixels of that image.",
        "    /// </summary>",
        "    /// <remarks>",
        "    /// Every image is square, with the flag drawn in its own proportions and transparent space around it.",
        "    /// The box is the bounds of the pixels that are at least half opaque, so the faint edge the artwork",
        "    /// antialiases a flag with stays outside it. Nearly every flag of a set shares one box per size, and the",
        "    /// few drawn in other proportions carry their own. The boxes of one flag are not a scaling of each",
        "    /// other - the small sizes are snapped to whole pixels - which is why every size has its own. The",
        "    /// packaged image of the Extras package is the 16 pixel image of the flat set.",
        "    /// </remarks>",
        "    private static FlagBox GetFlagContentBox(BitFlagImageSet set, int size, string? iso2) => (set, size, iso2) switch",
        "    {",
    ]

    for set_name in SETS:
        enum = f"BitFlagImageSet.{set_name.capitalize()}"
        for size in SIZES:
            per_code = boxes[(set_name, size)]
            default, _ = sorted(Counter(per_code.values()).items(), key=lambda kv: (-kv[1], kv[0]))[0]
            for code in sorted(per_code):
                if per_code[code] != default:
                    x, y, w, h = per_code[code]
                    lines.append(f"        ({enum}, {size}, \"{code}\") => new({x}, {y}, {w}, {h}),")
            x, y, w, h = default
            lines.append(f"        ({enum}, {size}, _) => new({x}, {y}, {w}, {h}),")

    lines += [
        "        _ => new(0, 0, size, size),",
        "    };",
        "}",
        "",
    ]

    # The encoding and line endings every C# source of the repository is checked out with.
    with open(BOXES_FILE, "w", encoding="utf-8-sig", newline="\r\n") as file:
        file.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("source", help="the folder of per-country folders of source png images")
    source = parser.parse_args().source

    codes, skipped = source_codes(source)
    extras = sorted(f[: -len(EXTRAS_SUFFIX)].upper() for f in os.listdir(EXTRAS_FLAGS) if f.endswith(EXTRAS_SUFFIX))
    if codes != extras:
        missing = sorted(set(extras) - set(codes))
        extra = sorted(set(codes) - set(extras))
        sys.exit(f"The source covers other countries than the packaged flags do. Missing: {missing}. Not packaged: {extra}.")

    os.makedirs(ASSETS_FLAGS, exist_ok=True)
    for name in os.listdir(ASSETS_FLAGS):
        if name.endswith(".webp"):
            os.remove(os.path.join(ASSETS_FLAGS, name))

    boxes = {(s, z): {} for s in SETS for z in SIZES}
    total = 0
    for code in codes:
        for set_name in SETS:
            for size in SIZES:
                with Image.open(os.path.join(source, code, f"{set_name}-{size}.png")) as png:
                    image = png.convert("RGBA")
                if image.size != (size, size):
                    sys.exit(f"{code}/{set_name}-{size}.png is {image.size[0]}x{image.size[1]} rather than {size}x{size}")
                path = os.path.join(ASSETS_FLAGS, f"{code}-{set_name}-{size}.webp")
                encode(image, set_name, path)
                total += os.path.getsize(path)
                boxes[(set_name, size)][code] = content_box(image)

    write_boxes(boxes)

    print(f"{len(codes)} countries, {len(codes) * len(SETS) * len(SIZES)} images, {total / 1024:.0f} KB")
    if skipped:
        print(f"Skipped incomplete source folders: {', '.join(skipped)}")


if __name__ == "__main__":
    main()
