trigger:
- develop

# https://bitplatform.dev/templates/devops

jobs:
- job: build
  displayName: 'CI build'

  pool:
    vmImage: 'ubuntu-24.04'

  steps:
  - task: UseDotNet@2
    displayName: 'Setup .NET'
    inputs:
      useGlobalJson: true
      workingDirectory: 'src'

  - task: NodeTool@1
    inputs:
      versionSpec: '23.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    displayName: 'Workload restore'
    inputs:
      targetType: 'inline'
      script: 'dotnet workload restore'

  - task: Bash@3
    displayName: 'Build'
    inputs:
      targetType: 'inline'
      script: 'dotnet build Boilerplate.slnx'

  - task: Bash@3
    displayName: 'Install Playwright'
    inputs:
      targetType: 'inline'
      script: 'pwsh src/Tests/bin/Debug/net10.0/playwright.ps1 install --with-deps'

  - task: Bash@3
    name: test
    displayName: 'Test'
    inputs:
      targetType: 'inline'
      script: 'cd src/Tests && dotnet test'

  - task: PublishPipelineArtifact@1
    displayName: 'Upload Tests Artifact'
    condition: failed()
    dependsOn: test
    inputs:
      targetPath: 'src/Tests/TestResults'
      artifactName: 'tests-artifact'