trigger:
- develop

# https://bitplatform.dev/templates/devops

variables:
  WEB_APP_DEPLOYMENT_TYPE: 'Spa'

jobs:
- job: build_blazor_server
  displayName: 'build blazor server'

  pool:
    vmImage: 'ubuntu-22.04'

  steps:
  - task: UseDotNet@2
    displayName: 'Setup .NET'
    inputs:
      useGlobalJson: true
      workingDirectory: 'src'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'
  
  - task: Bash@3
    displayName: 'Build'
    inputs:
      targetType: 'inline'
      script: 'dotnet build src/Client/Boilerplate.Client.Web/Boilerplate.Client.Web.csproj -p:Configuration=Release -p:WebAppDeploymentType="${{ variables.WEB_APP_DEPLOYMENT_TYPE }}"'

- job: build_blazor_hybrid_android
  displayName: 'build blazor hybrid (android)'

  pool:
    vmImage: 'windows-2022'

  steps:
  - task: UseDotNet@2
    displayName: 'Setup .NET'
    inputs:
      useGlobalJson: true
      workingDirectory: 'src'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    displayName: 'Install maui'
    inputs:
      targetType: 'inline'
      script: cd src && dotnet workload install maui
  
  - task: Bash@3
    displayName: 'Build'
    inputs:
      targetType: 'inline'
      script: 'dotnet build src/Client/Boilerplate.Client.App/Boilerplate.Client.App.csproj -p:RunAOTCompilation=false -p:BlazorMode=BlazorHybrid -p:Configuration=Release -f net8.0-android'

- job: build_blazor_hybrid_windows
  displayName: 'build blazor hybrid (windows)'

  pool:
    vmImage: 'windows-2022'

  steps:
  - task: UseDotNet@2
    displayName: 'Setup .NET'
    inputs:
      useGlobalJson: true
      workingDirectory: 'src'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    displayName: 'Install maui'
    inputs:
      targetType: 'inline'
      script: cd src && dotnet workload install maui
  
  - task: Bash@3
    displayName: 'Build'
    inputs:
      targetType: 'inline'
      script: 'dotnet build src/Client/Boilerplate.Client.App/Boilerplate.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -f net8.0-windows10.0.19041.0'

- job: build_blazor_hybrid_iOS
  displayName: 'build blazor hybrid (iOS)'

  pool:
    vmImage: 'macos-13'

  steps:
  - task: UseDotNet@2
    displayName: 'Setup .NET'
    inputs:
      useGlobalJson: true
      workingDirectory: 'src'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    displayName: 'Install maui'
    inputs:
      targetType: 'inline'
      script: cd src && dotnet workload install maui
  
  - task: Bash@3
    displayName: 'Build'
    inputs:
      targetType: 'inline'
      script: 'dotnet build src/Client/Boilerplate.Client.App/Boilerplate.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -f net8.0-ios'

- job: build_blazor_hybrid_maccatalyst
  displayName: 'build blazor hybrid (maccatalyst)'

  pool:
    vmImage: 'macos-13'

  steps:
  - task: UseDotNet@2
    displayName: 'Setup .NET'
    inputs:
      useGlobalJson: true
      workingDirectory: 'src'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    displayName: 'Install maui'
    inputs:
      targetType: 'inline'
      script: cd src && dotnet workload install maui
  
  - task: Bash@3
    displayName: 'Build'
    inputs:
      targetType: 'inline'
      script: 'dotnet build src/Client/Boilerplate.Client.App/Boilerplate.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -f net8.0-maccatalyst'

- job: build_blazor_api_wasm
  displayName: 'build blazor api + web assembly'

  pool:
    vmImage: 'ubuntu-22.04'

  steps:
  - task: UseDotNet@2
    displayName: 'Setup .NET'
    inputs:
      useGlobalJson: true
      workingDirectory: 'src'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    displayName: 'Install wasm'
    inputs:
      targetType: 'inline'
      script: 'cd src && dotnet workload install wasm-tools wasm-experimental'

  - task: Bash@3
    displayName: 'Switch to blazor web assembly'
    inputs:
      targetType: 'inline'
      script: sed -i 's/Microsoft.NET.Sdk.Web/Microsoft.NET.Sdk.BlazorWebAssembly/g' src/Client/Boilerplate.Client.Web/Boilerplate.Client.Web.csproj

  - task: Bash@3
    displayName: 'Build'
    inputs:
      targetType: 'inline'
      script: 'dotnet build src/Boilerplate.Server/Boilerplate.Server.csproj -p:Configuration=Release -p:BlazorMode=BlazorWebAssembly -p:WebAppDeploymentType="${{ variables.WEB_APP_DEPLOYMENT_TYPE }}"'