trigger:
- develop

# https://bitplatform.dev/templates/devops

jobs:
- job: build
  displayName: 'CI build'

  pool:
    vmImage: 'ubuntu-24.04'

  steps:
  - task: UseDotNet@2
    displayName: 'Setup .NET'
    inputs:
      useGlobalJson: true
      workingDirectory: 'src'

  - task: NodeTool@1
    inputs:
      versionSpec: '22.x'
    displayName: 'Install Node.js'
  
  - task: Bash@3
    displayName: 'Build'
    inputs:
      targetType: 'inline'
      script: 'dotnet build Boilerplate.sln -c Release'

  - task: Bash@3
    displayName: 'Install Playwright'
    inputs:
      targetType: 'inline'
      script: 'sudo pwsh src/Tests/bin/Debug/net8.0/playwright.ps1 install-deps && sudo pwsh src/Tests/bin/Debug/net8.0/playwright.ps1 install'

  - task: Bash@3
    displayName: 'Test'
    inputs:
      targetType: 'inline'
      script: 'dotnet test src/Tests/Boilerplate.Tests.csproj'