namespace Bit.BlazorUI;

/// <summary>
/// The parameters for the <see cref="BitSlider"/> component.
/// </summary>
/// <remarks>
/// Everything a group of sliders can share is here - the scale, the step, the marks, the colors, the sizes
/// and the accessible names of the two ends of a range. What each slider holds of its own is not: a value,
/// a default value, a name, the templates and the event callbacks stay on the markup of the slider itself.
/// </remarks>
public class BitSliderParams : BitInputBaseParams, IBitComponentParams
{
    /// <summary>
    /// Represents the parameter name used to identify the <see cref="BitSlider"/> cascading parameters within <see cref="BitParams"/>.
    /// </summary>
    /// <remarks>
    /// This constant is typically used when referencing or accessing the BitSlider value in
    /// parameterized APIs or configuration settings. Using this constant helps ensure consistency and reduces the risk
    /// of typographical errors.
    /// </remarks>
    public const string ParamName = $"{nameof(BitParams)}.{nameof(BitSlider)}";



    public string Name => ParamName;



    /// <summary>
    /// A description of the slider for the benefit of screen readers, rendered into a visually hidden element
    /// that every thumb references through its <c>aria-describedby</c> attribute.
    /// </summary>
    public string? AriaDescription { get; set; }

    /// <summary>
    /// A text description of the Slider number value for the benefit of screen readers, which becomes the
    /// <c>aria-valuetext</c> of every thumb.
    /// </summary>
    public Func<double, string>? AriaValueText { get; set; }

    /// <summary>
    /// If true, the slider automatically receives focus when the page renders.
    /// </summary>
    public bool? AutoFocus { get; set; }

    /// <summary>
    /// Custom CSS classes for different parts of the slider.
    /// </summary>
    public BitSliderClassStyles? Classes { get; set; }

    /// <summary>
    /// The general color of the slider, applied to the filled part of the track and to the thumbs.
    /// </summary>
    public BitColor? Color { get; set; }

    /// <summary>
    /// Lets the filled band between the two thumbs of a ranged slider be dragged bodily.
    /// </summary>
    public bool? DraggableTrack { get; set; }

    /// <summary>
    /// Builds the text of every label the slider draws from the value it stands for. Takes precedence over
    /// <see cref="ValueFormat"/>.
    /// </summary>
    public Func<double, string>? GetValueText { get; set; }

    /// <summary>
    /// Fills the track from the far end instead of from the near one.
    /// </summary>
    public bool? Inverted { get; set; }

    /// <summary>
    /// Attaches the origin of the filled part of the track to zero.
    /// </summary>
    public bool? IsOriginFromZero { get; set; }

    /// <summary>
    /// Gives the slider a second thumb, so what it selects is a range rather than a single value.
    /// </summary>
    public bool? IsRanged { get; set; }

    /// <summary>
    /// Stands the slider upright and fills it from the bottom up.
    /// </summary>
    public bool? IsVertical { get; set; }

    /// <summary>
    /// The distance the larger keyboard jumps cover: <c>Page Up</c> and <c>Page Down</c>, and an arrow key
    /// held with <c>Shift</c>.
    /// </summary>
    public double? LargeStep { get; set; }

    /// <summary>
    /// The accessible name of the lower thumb of a ranged slider.
    /// </summary>
    public string? LowerAriaLabel { get; set; }

    /// <summary>
    /// The marks drawn along the track of the slider, each optionally carrying a label under it.
    /// </summary>
    public IEnumerable<BitSliderMark>? Marks { get; set; }

    /// <summary>
    /// The interval between the marks generated by <see cref="ShowMarks"/>.
    /// </summary>
    public double? MarkStep { get; set; }

    /// <summary>
    /// The max value of the slider.
    /// </summary>
    public double? Max { get; set; }

    /// <summary>
    /// The largest distance the two thumbs of a ranged slider are allowed to be apart.
    /// </summary>
    public double? MaxRange { get; set; }

    /// <summary>
    /// The min value of the slider.
    /// </summary>
    public double? Min { get; set; }

    /// <summary>
    /// The smallest distance the two thumbs of a ranged slider are allowed to be apart.
    /// </summary>
    public double? MinRange { get; set; }

    /// <summary>
    /// Leaves the track unfilled, so the slider is a bare rail with a thumb on it.
    /// </summary>
    public bool? NoFill { get; set; }

    /// <summary>
    /// Stops the two thumbs of a ranged slider from crossing over each other.
    /// </summary>
    public bool? NoSwap { get; set; }

    /// <summary>
    /// The value the filled part of the track grows out of, instead of the near end of the track.
    /// </summary>
    public double? Origin { get; set; }

    /// <summary>
    /// Lets a thumb of a ranged slider push the other one along instead of stopping against it.
    /// </summary>
    public bool? Pushable { get; set; }

    /// <summary>
    /// Restricts the values the user can pick to the marks alone.
    /// </summary>
    public bool? RestrictToMarks { get; set; }

    /// <summary>
    /// Labels the generated marks of <see cref="ShowMarks"/> with their own values.
    /// </summary>
    public bool? ShowMarkLabels { get; set; }

    /// <summary>
    /// Draws a mark at every <see cref="MarkStep"/> (or every <see cref="Step"/> when that is not set).
    /// </summary>
    public bool? ShowMarks { get; set; }

    /// <summary>
    /// Whether to show the value beside the slider.
    /// </summary>
    public bool? ShowValue { get; set; }

    /// <summary>
    /// Size of the slider, which scales its track, thumbs and labels together.
    /// </summary>
    public BitSize? Size { get; set; }

    /// <summary>
    /// Additional HTML attributes for the slider box, the element the track and the inputs are laid inside of.
    /// </summary>
    public Dictionary<string, object>? SliderBoxHtmlAttributes { get; set; }

    /// <summary>
    /// The difference between the two adjacent values of the slider.
    /// </summary>
    public double? Step { get; set; }

    /// <summary>
    /// Custom CSS styles for different parts of the slider.
    /// </summary>
    public BitSliderClassStyles? Styles { get; set; }

    /// <summary>
    /// Decides when the floating label that rides along with the thumb is shown.
    /// </summary>
    public BitSliderThumbLabel? ThumbLabel { get; set; }

    /// <summary>
    /// The accessible name of the upper thumb of a ranged slider.
    /// </summary>
    public string? UpperAriaLabel { get; set; }

    /// <summary>
    /// Custom format for the displayed value of the slider, applied to the value labels, the mark labels and
    /// the floating thumb labels alike.
    /// </summary>
    public string? ValueFormat { get; set; }



    /// <summary>
    /// Updates the properties of the specified <see cref="BitSlider"/> instance with any values that have been set
    /// on this object, if those properties have not already been set on the <see cref="BitSlider"/>.
    /// </summary>
    /// <remarks>
    /// Only properties that have a value set and have not already been set on the <paramref name="bitSlider"/> will
    /// be updated. This method does not overwrite existing values on <paramref name="bitSlider"/>.
    /// </remarks>
    /// <param name="bitSlider">
    /// The <see cref="BitSlider"/> instance whose properties will be updated. Cannot be null.
    /// </param>
    public void UpdateParameters(BitSlider bitSlider)
    {
        if (bitSlider is null) return;

        UpdateInputParameters(bitSlider);

        if (AriaDescription.HasValue() && bitSlider.HasNotBeenSet(nameof(AriaDescription)))
        {
            bitSlider.AriaDescription = AriaDescription;
        }

        if (AriaValueText is not null && bitSlider.HasNotBeenSet(nameof(AriaValueText)))
        {
            bitSlider.AriaValueText = AriaValueText;
        }

        if (AutoFocus.HasValue && bitSlider.HasNotBeenSet(nameof(AutoFocus)))
        {
            bitSlider.AutoFocus = AutoFocus.Value;
        }

        if (Classes is not null && bitSlider.HasNotBeenSet(nameof(Classes)))
        {
            bitSlider.Classes = Classes;

            bitSlider.ClassBuilder.Reset();
        }

        if (Color.HasValue && bitSlider.HasNotBeenSet(nameof(Color)))
        {
            bitSlider.Color = Color.Value;

            bitSlider.ClassBuilder.Reset();
        }

        if (DraggableTrack.HasValue && bitSlider.HasNotBeenSet(nameof(DraggableTrack)))
        {
            bitSlider.DraggableTrack = DraggableTrack.Value;
        }

        if (GetValueText is not null && bitSlider.HasNotBeenSet(nameof(GetValueText)))
        {
            bitSlider.GetValueText = GetValueText;
        }

        if (Inverted.HasValue && bitSlider.HasNotBeenSet(nameof(Inverted)))
        {
            bitSlider.Inverted = Inverted.Value;

            bitSlider.ClassBuilder.Reset();
        }

        if (IsOriginFromZero.HasValue && bitSlider.HasNotBeenSet(nameof(IsOriginFromZero)))
        {
            bitSlider.IsOriginFromZero = IsOriginFromZero.Value;
        }

        if (IsRanged.HasValue && bitSlider.HasNotBeenSet(nameof(IsRanged)))
        {
            bitSlider.IsRanged = IsRanged.Value;

            bitSlider.ClassBuilder.Reset();
        }

        if (IsVertical.HasValue && bitSlider.HasNotBeenSet(nameof(IsVertical)))
        {
            bitSlider.IsVertical = IsVertical.Value;

            bitSlider.ClassBuilder.Reset();
        }

        if (LargeStep.HasValue && bitSlider.HasNotBeenSet(nameof(LargeStep)))
        {
            bitSlider.LargeStep = LargeStep.Value;
        }

        if (LowerAriaLabel.HasValue() && bitSlider.HasNotBeenSet(nameof(LowerAriaLabel)))
        {
            bitSlider.LowerAriaLabel = LowerAriaLabel;
        }

        if (Marks is not null && bitSlider.HasNotBeenSet(nameof(Marks)))
        {
            bitSlider.Marks = Marks;
        }

        if (MarkStep.HasValue && bitSlider.HasNotBeenSet(nameof(MarkStep)))
        {
            bitSlider.MarkStep = MarkStep.Value;
        }

        if (Max.HasValue && bitSlider.HasNotBeenSet(nameof(Max)))
        {
            bitSlider.Max = Max.Value;
        }

        if (MaxRange.HasValue && bitSlider.HasNotBeenSet(nameof(MaxRange)))
        {
            bitSlider.MaxRange = MaxRange.Value;
        }

        if (Min.HasValue && bitSlider.HasNotBeenSet(nameof(Min)))
        {
            bitSlider.Min = Min.Value;
        }

        if (MinRange.HasValue && bitSlider.HasNotBeenSet(nameof(MinRange)))
        {
            bitSlider.MinRange = MinRange.Value;
        }

        if (NoFill.HasValue && bitSlider.HasNotBeenSet(nameof(NoFill)))
        {
            bitSlider.NoFill = NoFill.Value;
        }

        if (NoSwap.HasValue && bitSlider.HasNotBeenSet(nameof(NoSwap)))
        {
            bitSlider.NoSwap = NoSwap.Value;
        }

        if (Origin.HasValue && bitSlider.HasNotBeenSet(nameof(Origin)))
        {
            bitSlider.Origin = Origin.Value;
        }

        if (Pushable.HasValue && bitSlider.HasNotBeenSet(nameof(Pushable)))
        {
            bitSlider.Pushable = Pushable.Value;
        }

        if (RestrictToMarks.HasValue && bitSlider.HasNotBeenSet(nameof(RestrictToMarks)))
        {
            bitSlider.RestrictToMarks = RestrictToMarks.Value;
        }

        if (ShowMarkLabels.HasValue && bitSlider.HasNotBeenSet(nameof(ShowMarkLabels)))
        {
            bitSlider.ShowMarkLabels = ShowMarkLabels.Value;
        }

        if (ShowMarks.HasValue && bitSlider.HasNotBeenSet(nameof(ShowMarks)))
        {
            bitSlider.ShowMarks = ShowMarks.Value;
        }

        if (ShowValue.HasValue && bitSlider.HasNotBeenSet(nameof(ShowValue)))
        {
            bitSlider.ShowValue = ShowValue.Value;
        }

        if (Size.HasValue && bitSlider.HasNotBeenSet(nameof(Size)))
        {
            bitSlider.Size = Size.Value;

            bitSlider.ClassBuilder.Reset();
        }

        if (SliderBoxHtmlAttributes is not null && bitSlider.HasNotBeenSet(nameof(SliderBoxHtmlAttributes)))
        {
            bitSlider.SliderBoxHtmlAttributes = SliderBoxHtmlAttributes;
        }

        if (Step.HasValue && bitSlider.HasNotBeenSet(nameof(Step)))
        {
            bitSlider.Step = Step.Value;
        }

        if (Styles is not null && bitSlider.HasNotBeenSet(nameof(Styles)))
        {
            bitSlider.Styles = Styles;

            bitSlider.StyleBuilder.Reset();
        }

        if (ThumbLabel.HasValue && bitSlider.HasNotBeenSet(nameof(ThumbLabel)))
        {
            bitSlider.ThumbLabel = ThumbLabel.Value;

            bitSlider.ClassBuilder.Reset();
        }

        if (UpperAriaLabel.HasValue() && bitSlider.HasNotBeenSet(nameof(UpperAriaLabel)))
        {
            bitSlider.UpperAriaLabel = UpperAriaLabel;
        }

        if (ValueFormat.HasValue() && bitSlider.HasNotBeenSet(nameof(ValueFormat)))
        {
            bitSlider.ValueFormat = ValueFormat;
        }
    }
}
