//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boilerplate.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Boilerplate.Shared.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        public static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}?.
        /// </summary>
        public static string AreYouSureWannaDelete {
            get {
                return ResourceManager.GetString("AreYouSureWannaDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete category {0}.
        /// </summary>
        public static string AreYouSureWannaDeleteCategory {
            get {
                return ResourceManager.GetString("AreYouSureWannaDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete product {0}.
        /// </summary>
        public static string AreYouSureWannaDeleteProduct {
            get {
                return ResourceManager.GetString("AreYouSureWannaDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string BadRequestException {
            get {
                return ResourceManager.GetString("BadRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesPageTitle {
            get {
                return ResourceManager.GetString("CategoriesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category entity could not be found.
        /// </summary>
        public static string CategoryCouldNotBeFound {
            get {
                return ResourceManager.GetString("CategoryCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category contain some products, so you can&apos;t delete it.
        /// </summary>
        public static string CategoryNotEmpty {
            get {
                return ResourceManager.GetString("CategoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email.
        /// </summary>
        public static string ChangeEmailTitle {
            get {
                return ResourceManager.GetString("ChangeEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change phone number.
        /// </summary>
        public static string ChangePhoneNumberTitle {
            get {
                return ResourceManager.GetString("ChangePhoneNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is your change phone number token in Boilerplate..
        /// </summary>
        public static string ChangePhoneNumberTokenSmsText {
            get {
                return ResourceManager.GetString("ChangePhoneNumberTokenSmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your Spam/Junk, if you could not find it in the Inbox..
        /// </summary>
        public static string CheckSpamMailMessage {
            get {
                return ResourceManager.GetString("CheckSpamMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; do not match..
        /// </summary>
        public static string CompareAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CompareAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string ConfirmEmailHeaderText {
            get {
                return ResourceManager.GetString("ConfirmEmailHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email by typing the token here..
        /// </summary>
        public static string ConfirmEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a confirmation token to your email address..
        /// </summary>
        public static string ConfirmEmailSubtitle {
            get {
                return ResourceManager.GetString("ConfirmEmailSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have a token?.
        /// </summary>
        public static string ConfirmMessageInProfile {
            get {
                return ResourceManager.GetString("ConfirmMessageInProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to confirm an account?.
        /// </summary>
        public static string ConfirmMessageInSignUp {
            get {
                return ResourceManager.GetString("ConfirmMessageInSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string ConfirmPhoneHeaderText {
            get {
                return ResourceManager.GetString("ConfirmPhoneHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your phone number by typing the token here..
        /// </summary>
        public static string ConfirmPhoneMessage {
            get {
                return ResourceManager.GetString("ConfirmPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a confirmation token to your phone..
        /// </summary>
        public static string ConfirmPhoneSubtitle {
            get {
                return ResourceManager.GetString("ConfirmPhoneSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is your confirm phone number token in Boilerplate..
        /// </summary>
        public static string ConfirmPhoneTokenSmsText {
            get {
                return ResourceManager.GetString("ConfirmPhoneTokenSmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request could not be processed because of conflict in the request.
        /// </summary>
        public static string ConflictException {
            get {
                return ResourceManager.GetString("ConflictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current email.
        /// </summary>
        public static string CurrentEmail {
            get {
                return ResourceManager.GetString("CurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current phone number.
        /// </summary>
        public static string CurrentPhoneNumber {
            get {
                return ResourceManager.GetString("CurrentPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current session.
        /// </summary>
        public static string CurrentSession {
            get {
                return ResourceManager.GetString("CurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom color.
        /// </summary>
        public static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default color picker.
        /// </summary>
        public static string DefaultColorPicker {
            get {
                return ResourceManager.GetString("DefaultColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account?.
        /// </summary>
        public static string DeleteAccountPrompt {
            get {
                return ResourceManager.GetString("DeleteAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete category.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product.
        /// </summary>
        public static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete todo item.
        /// </summary>
        public static string DeleteTodoItem {
            get {
                return ResourceManager.GetString("DeleteTodoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have an account?.
        /// </summary>
        public static string DontHaveAccountMessage {
            get {
                return ResourceManager.GetString("DontHaveAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email or phone number is already taken..
        /// </summary>
        public static string DuplicateEmailOrPhoneNumber {
            get {
                return ResourceManager.GetString("DuplicateEmailOrPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        public static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EditProfileTitle {
            get {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either provide email or phone number..
        /// </summary>
        public static string EitherProvideEmailOrPhoneNumber {
            get {
                return ResourceManager.GetString("EitherProvideEmailOrPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either provide password or OTP.
        /// </summary>
        public static string EitherProvidePasswordOrOtp {
            get {
                return ResourceManager.GetString("EitherProvidePasswordOrOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either provide username, email or phone number..
        /// </summary>
        public static string EitherProvideUserNameOrEmailOrPhoneNumber {
            get {
                return ResourceManager.GetString("EitherProvideUserNameOrEmailOrPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
        /// </summary>
        public static string EmailAddressAttribute_ValidationError {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is already confirmed..
        /// </summary>
        public static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation Failed!.
        /// </summary>
        public static string EmailConfirmationFailedMessage {
            get {
                return ResourceManager.GetString("EmailConfirmationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now login with your account..
        /// </summary>
        public static string EmailConfirmationSuccessMessage {
            get {
                return ResourceManager.GetString("EmailConfirmationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address ({0}) has been confirmed..
        /// </summary>
        public static string EmailConfirmationSuccessTitle {
            get {
                return ResourceManager.GetString("EmailConfirmationSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation.
        /// </summary>
        public static string EmailConfirmationTitle {
            get {
                return ResourceManager.GetString("EmailConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed Successfully!.
        /// </summary>
        public static string EmailConfirmedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email address.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Token.
        /// </summary>
        public static string EmailToken {
            get {
                return ResourceManager.GetString("EmailToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email Address.
        /// </summary>
        public static string EmailTokenConfirmButtonText {
            get {
                return ResourceManager.GetString("EmailTokenConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email token.
        /// </summary>
        public static string EmailTokenPlaceholder {
            get {
                return ResourceManager.GetString("EmailTokenPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter category name.
        /// </summary>
        public static string EnterCategoryName {
            get {
                return ResourceManager.GetString("EnterCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product name.
        /// </summary>
        public static string EnterProductName {
            get {
                return ResourceManager.GetString("EnterProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading file.
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the requested resource is forbidden.
        /// </summary>
        public static string ForbiddenException {
            get {
                return ResourceManager.GetString("ForbiddenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address or phone number so we can send a reset password token to you..
        /// </summary>
        public static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string GenderOther {
            get {
                return ResourceManager.GetString("GenderOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repo.
        /// </summary>
        public static string GitHubRepo {
            get {
                return ResourceManager.GetString("GitHubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with GitHub.
        /// </summary>
        public static string GitHubSignInButtonText {
            get {
                return ResourceManager.GetString("GitHubSignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up with GitHub.
        /// </summary>
        public static string GitHubSignUpButtonText {
            get {
                return ResourceManager.GetString("GitHubSignUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Google.
        /// </summary>
        public static string GoogleSignInButtonText {
            get {
                return ResourceManager.GetString("GoogleSignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up with Google.
        /// </summary>
        public static string GoogleSignUpButtonText {
            get {
                return ResourceManager.GetString("GoogleSignUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to today.
        /// </summary>
        public static string GoToToday {
            get {
                return ResourceManager.GetString("GoToToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your multi-mode (WASM, Server, Hybrid, pre-rendering) Blazor app easily in the shortest time ever!.
        /// </summary>
        public static string HomeMessage {
            get {
                return ResourceManager.GetString("HomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boilerplate Home.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the confirmation token either is invalid or has expired..
        /// </summary>
        public static string InvalidConfirmationTokenMessage {
            get {
                return ResourceManager.GetString("InvalidConfirmationTokenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to pass the Google reCAPTCHA challenge..
        /// </summary>
        public static string InvalidGoogleRecaptchaChallenge {
            get {
                return ResourceManager.GetString("InvalidGoogleRecaptchaChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Google reCAPTCHA response..
        /// </summary>
        public static string InvalidGoogleRecaptchaResponse {
            get {
                return ResourceManager.GetString("InvalidGoogleRecaptchaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user credentials.
        /// </summary>
        public static string InvalidUserCredentials {
            get {
                return ResourceManager.GetString("InvalidUserCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days category count.
        /// </summary>
        public static string Last30DaysCategoryCount {
            get {
                return ResourceManager.GetString("Last30DaysCategoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days product count.
        /// </summary>
        public static string Last30DaysProductCount {
            get {
                return ResourceManager.GetString("Last30DaysProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLengthAttribute must have a Length value that is greater than zero. Use MaxLength() without parameters to indicate that the string or array can have the maximum allowable length..
        /// </summary>
        public static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a minimum length of &apos;{1}&apos;..
        /// </summary>
        public static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new email.
        /// </summary>
        public static string NewEmailPlaceholder {
            get {
                return ResourceManager.GetString("NewEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New phone number.
        /// </summary>
        public static string NewPhoneNumber {
            get {
                return ResourceManager.GetString("NewPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new phone number.
        /// </summary>
        public static string NewPhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("NewPhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available.
        /// </summary>
        public static string NewVersionIsAvailable {
            get {
                return ResourceManager.GetString("NewVersionIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing here..
        /// </summary>
        public static string NotFoundText {
            get {
                return ResourceManager.GetString("NotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No todos yet.
        /// </summary>
        public static string NoTodos {
            get {
                return ResourceManager.GetString("NoTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven’t you received the confirmation email?.
        /// </summary>
        public static string NotReceivedConfirmationEmailMessage {
            get {
                return ResourceManager.GetString("NotReceivedConfirmationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven’t you received the token on your phone?.
        /// </summary>
        public static string NotReceivedConfirmationPhoneMessage {
            get {
                return ResourceManager.GetString("NotReceivedConfirmationPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Edit profile.
        /// </summary>
        public static string OfflineEditProfileTitle {
            get {
                return ResourceManager.GetString("OfflineEditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other sessions.
        /// </summary>
        public static string OtherSessions {
            get {
                return ResourceManager.GetString("OtherSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP.
        /// </summary>
        public static string Otp {
            get {
                return ResourceManager.GetString("Otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP.
        /// </summary>
        public static string OtpPlaceholder {
            get {
                return ResourceManager.GetString("OtpPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An OTP has been generated and sent to you..
        /// </summary>
        public static string OtpSentMessage {
            get {
                return ResourceManager.GetString("OtpSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is your OTP in Boilerplate..
        /// </summary>
        public static string OtpSmsText {
            get {
                return ResourceManager.GetString("OtpSmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password changed successfully..
        /// </summary>
        public static string PasswordChangedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid phone number..
        /// </summary>
        public static string PhoneAttribute_ValidationError {
            get {
                return ResourceManager.GetString("PhoneAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now login with your account..
        /// </summary>
        public static string PhoneConfirmationSuccessMessage {
            get {
                return ResourceManager.GetString("PhoneConfirmationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number ({0}) has been confirmed..
        /// </summary>
        public static string PhoneConfirmationSuccessTitle {
            get {
                return ResourceManager.GetString("PhoneConfirmationSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number is already confirmed..
        /// </summary>
        public static string PhoneNumberAlreadyConfirmed {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        public static string PhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("PhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Token.
        /// </summary>
        public static string PhoneToken {
            get {
                return ResourceManager.GetString("PhoneToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Phone Number.
        /// </summary>
        public static string PhoneTokenConfirmButtonText {
            get {
                return ResourceManager.GetString("PhoneTokenConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone token.
        /// </summary>
        public static string PhoneTokenPlaceholder {
            get {
                return ResourceManager.GetString("PhoneTokenPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product entity could not be found.
        /// </summary>
        public static string ProductCouldNotBeFound {
            get {
                return ResourceManager.GetString("ProductCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product sales.
        /// </summary>
        public static string ProductSales {
            get {
                return ResourceManager.GetString("ProductSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chart shows the sale number of each product..
        /// </summary>
        public static string ProductSalesText {
            get {
                return ResourceManager.GetString("ProductSalesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products count.
        /// </summary>
        public static string ProductsCount {
            get {
                return ResourceManager.GetString("ProductsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products count per category chart.
        /// </summary>
        public static string ProductsCountPerCategoryChart {
            get {
                return ResourceManager.GetString("ProductsCountPerCategoryChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chart shows the number of products in each category..
        /// </summary>
        public static string ProductsCountPerCategoryChartText {
            get {
                return ResourceManager.GetString("ProductsCountPerCategoryChartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ProductsPageTitle {
            get {
                return ResourceManager.GetString("ProductsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products percentage per category.
        /// </summary>
        public static string ProductsPercentagePerCategory {
            get {
                return ResourceManager.GetString("ProductsPercentagePerCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chart shows the percentage of products in each category..
        /// </summary>
        public static string ProductsPercentagePerCategoryText {
            get {
                return ResourceManager.GetString("ProductsPercentagePerCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully..
        /// </summary>
        public static string ProfileUpdatedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}..
        /// </summary>
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently.
        /// </summary>
        public static string Recently {
            get {
                return ResourceManager.GetString("Recently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove session.
        /// </summary>
        public static string RemoveSession {
            get {
                return ResourceManager.GetString("RemoveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session removed successfully.
        /// </summary>
        public static string RemoveSessionSuccessMessage {
            get {
                return ResourceManager.GetString("RemoveSessionSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation token has been re-sent to your email address..
        /// </summary>
        public static string ResendConfirmationEmailTokenMessage {
            get {
                return ResourceManager.GetString("ResendConfirmationEmailTokenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation token has been re-sent to your phone..
        /// </summary>
        public static string ResendConfirmationPhoneTokenMessage {
            get {
                return ResourceManager.GetString("ResendConfirmationPhoneTokenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Email Token.
        /// </summary>
        public static string ResendEmailTokenButtonText {
            get {
                return ResourceManager.GetString("ResendEmailTokenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Phone Token.
        /// </summary>
        public static string ResendPhoneTokenButtonText {
            get {
                return ResourceManager.GetString("ResendPhoneTokenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string ResetPasswordButtonText {
            get {
                return ResourceManager.GetString("ResetPasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please submit the token together with your new password here..
        /// </summary>
        public static string ResetPasswordMessage {
            get {
                return ResourceManager.GetString("ResetPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have a reset password token?.
        /// </summary>
        public static string ResetPasswordMessageInForgot {
            get {
                return ResourceManager.GetString("ResetPasswordMessageInForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a token to your phone or email..
        /// </summary>
        public static string ResetPasswordSubtitle {
            get {
                return ResourceManager.GetString("ResetPasswordSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now login with your password..
        /// </summary>
        public static string ResetPasswordSuccessBody {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string ResetPasswordSuccessTitle {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reset password token has been sent to your email address..
        /// </summary>
        public static string ResetPasswordTokenSentMessage {
            get {
                return ResourceManager.GetString("ResetPasswordTokenSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is your reset password token in Boilerplate..
        /// </summary>
        public static string ResetPasswordTokenSmsText {
            get {
                return ResourceManager.GetString("ResetPasswordTokenSmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string ResourceNotFoundException {
            get {
                return ResourceManager.GetString("ResourceNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request data is not valid.
        /// </summary>
        public static string ResourceValidationException {
            get {
                return ResourceManager.GetString("ResourceValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while communicating with server.
        /// </summary>
        public static string RestException {
            get {
                return ResourceManager.GetString("RestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on name.
        /// </summary>
        public static string SearchOnName {
            get {
                return ResourceManager.GetString("SearchOnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your birth date.
        /// </summary>
        public static string SelectBirthDate {
            get {
                return ResourceManager.GetString("SelectBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send OTP and Magic link.
        /// </summary>
        public static string SendOtpButtonText {
            get {
                return ResourceManager.GetString("SendOtpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server..
        /// </summary>
        public static string ServerConnectionException {
            get {
                return ResourceManager.GetString("ServerConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in as different user.
        /// </summary>
        public static string SignInAsDifferentUser {
            get {
                return ResourceManager.GetString("SignInAsDifferentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string SignInMessageInSignUp {
            get {
                return ResourceManager.GetString("SignInMessageInSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Sign out?.
        /// </summary>
        public static string SignOutPrompt {
            get {
                return ResourceManager.GetString("SignOutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SingUpTitle {
            get {
                return ResourceManager.GetString("SingUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can go back to the application now.
        /// </summary>
        public static string SocialSignedInMessageBody {
            get {
                return ResourceManager.GetString("SocialSignedInMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The social sign-in is done.
        /// </summary>
        public static string SocialSignedInMessageTitle {
            get {
                return ResourceManager.GetString("SocialSignedInMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social signed in.
        /// </summary>
        public static string SocialSignedInTitle {
            get {
                return ResourceManager.GetString("SocialSignedInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is accept terms?.
        /// </summary>
        public static string TermsAccepted {
            get {
                return ResourceManager.GetString("TermsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the.
        /// </summary>
        public static string TermsMessage {
            get {
                return ResourceManager.GetString("TermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator app.
        /// </summary>
        public static string TfaAuthAppHeader {
            get {
                return ResourceManager.GetString("TfaAuthAppHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        public static string TfaAuthAppResetKeyButtonText {
            get {
                return ResourceManager.GetString("TfaAuthAppResetKeyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process disables 2FA until you verify your authenticator app. If you do not complete your authenticator app configuration you may lose access to your account..
        /// </summary>
        public static string TfaAuthAppWarning {
            get {
                return ResourceManager.GetString("TfaAuthAppWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you reset your authenticator key your authenticator app will not work until you reconfigure it..
        /// </summary>
        public static string TfaAuthAppWarningTitle {
            get {
                return ResourceManager.GetString("TfaAuthAppWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticator app has been verified..
        /// </summary>
        public static string TfaAuthenticatorAppVerifiedMessage {
            get {
                return ResourceManager.GetString("TfaAuthenticatorAppVerifiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a two-factor authenticator app like Google Authenticator for {0} and {1}..
        /// </summary>
        public static string TfaConfigureAutAppStep1 {
            get {
                return ResourceManager.GetString("TfaConfigureAutAppStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan/click the QR Code or enter the following key into your two factor authenticator app (spaces and casing do not matter):.
        /// </summary>
        public static string TfaConfigureAutAppStep2 {
            get {
                return ResourceManager.GetString("TfaConfigureAutAppStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have scanned the QR code or input the key above, your two factor authentication app will provide you with a unique code. Enter the code in the confirmation box below..
        /// </summary>
        public static string TfaConfigureAutAppStep3 {
            get {
                return ResourceManager.GetString("TfaConfigureAutAppStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use an authenticator app go through the following steps:.
        /// </summary>
        public static string TfaConfigureAutAppSubtitle {
            get {
                return ResourceManager.GetString("TfaConfigureAutAppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure authenticator app.
        /// </summary>
        public static string TfaConfigureAutAppTitle {
            get {
                return ResourceManager.GetString("TfaConfigureAutAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code:.
        /// </summary>
        public static string TfaConfigureAutAppVerificationCodeLabel {
            get {
                return ResourceManager.GetString("TfaConfigureAutAppVerificationCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code..
        /// </summary>
        public static string TfaConfigureAutAppVerificationCodePlaceholder {
            get {
                return ResourceManager.GetString("TfaConfigureAutAppVerificationCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string TfaConfigureAutAppVerifyButtonText {
            get {
                return ResourceManager.GetString("TfaConfigureAutAppVerifyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string TfaDisable2faButtonText {
            get {
                return ResourceManager.GetString("TfaDisable2faButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string TfaDisable2faHeader {
            get {
                return ResourceManager.GetString("TfaDisable2faHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should reset your authenticator keys in the previous tab..
        /// </summary>
        public static string TfaDisable2faWarning {
            get {
                return ResourceManager.GetString("TfaDisable2faWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action only disables 2FA..
        /// </summary>
        public static string TfaDisable2faWarningTitle {
            get {
                return ResourceManager.GetString("TfaDisable2faWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No 2fa token was provided by the request. A valid 2fa token is required to enable 2fa..
        /// </summary>
        public static string TfaEmptyCodeError {
            get {
                return ResourceManager.GetString("TfaEmptyCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your authenticator code:.
        /// </summary>
        public static string TfaEnterCodeInSignInMessage {
            get {
                return ResourceManager.GetString("TfaEnterCodeInSignInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or enter your recovery code:.
        /// </summary>
        public static string TfaEnterRecoveryCodeInSignInMessage {
            get {
                return ResourceManager.GetString("TfaEnterRecoveryCodeInSignInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 2fa token provided by the request was invalid. A valid 2fa token is required to enable 2fa..
        /// </summary>
        public static string TfaInvalidCodeError {
            get {
                return ResourceManager.GetString("TfaInvalidCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login is protected with an authenticator app..
        /// </summary>
        public static string TfaProtectedSignInSubtitle {
            get {
                return ResourceManager.GetString("TfaProtectedSignInSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Recovery Codes.
        /// </summary>
        public static string TfaRecoveryCodesGenerateButtonText {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesGenerateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should reset your authenticator keys in the next tab..
        /// </summary>
        public static string TfaRecoveryCodesGenerateWraning {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesGenerateWraning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery codes.
        /// </summary>
        public static string TfaRecoveryCodesHeader {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can generate a new set of recovery codes..
        /// </summary>
        public static string TfaRecoveryCodesOneLeftSubtitle {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesOneLeftSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 recovery code left..
        /// </summary>
        public static string TfaRecoveryCodesOneLeftTitle {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesOneLeftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should generate a new set of recovery codes..
        /// </summary>
        public static string TfaRecoveryCodesThreeLeftSubtitle {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesThreeLeftSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} recovery codes left..
        /// </summary>
        public static string TfaRecoveryCodesThreeLeftTitle {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesThreeLeftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery codes:.
        /// </summary>
        public static string TfaRecoveryCodesTitle {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you lose your authenticator device and don&apos;t have the recovery codes you will lose access to your account..
        /// </summary>
        public static string TfaRecoveryCodesWarning {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put these codes in a safe place..
        /// </summary>
        public static string TfaRecoveryCodesWarningTitle {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must generate a new set of recovery codes before you can log in with a recovery code..
        /// </summary>
        public static string TfaRecoveryCodesZeroLeftSubtitle {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesZeroLeftSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recovery codes left..
        /// </summary>
        public static string TfaRecoveryCodesZeroLeftTitle {
            get {
                return ResourceManager.GetString("TfaRecoveryCodesZeroLeftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting the 2fa shared key must disable 2fa until a 2fa token based on the new shared key is validated..
        /// </summary>
        public static string TfaResetSharedKeyError {
            get {
                return ResourceManager.GetString("TfaResetSharedKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate and Send 2FA Token.
        /// </summary>
        public static string TfaTokenGenerateButtonText {
            get {
                return ResourceManager.GetString("TfaTokenGenerateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 2FA token has been generated and sent to you..
        /// </summary>
        public static string TfaTokenSentMessage {
            get {
                return ResourceManager.GetString("TfaTokenSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access to authenticator app?.
        /// </summary>
        public static string TfaTokenSignInTitle {
            get {
                return ResourceManager.GetString("TfaTokenSignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a todo.
        /// </summary>
        public static string TodoAddPlaceholder {
            get {
                return ResourceManager.GetString("TodoAddPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo item could not be found.
        /// </summary>
        public static string ToDoItemCouldNotBeFound {
            get {
                return ResourceManager.GetString("ToDoItemCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search some todo....
        /// </summary>
        public static string TodoSearchPlaceholder {
            get {
                return ResourceManager.GetString("TodoSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo.
        /// </summary>
        public static string TodoTitle {
            get {
                return ResourceManager.GetString("TodoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter token.
        /// </summary>
        public static string TokenPlaceholder {
            get {
                return ResourceManager.GetString("TokenPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests.
        /// </summary>
        public static string TooManyRequestsExceptions {
            get {
                return ResourceManager.GetString("TooManyRequestsExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total categories.
        /// </summary>
        public static string TotalCategories {
            get {
                return ResourceManager.GetString("TotalCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total products.
        /// </summary>
        public static string TotalProducts {
            get {
                return ResourceManager.GetString("TotalProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Twitter (X).
        /// </summary>
        public static string TwitterSignInButtonText {
            get {
                return ResourceManager.GetString("TwitterSignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up with Twitter (X).
        /// </summary>
        public static string TwitterSignUpButtonText {
            get {
                return ResourceManager.GetString("TwitterSignUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA.
        /// </summary>
        public static string TwoFactorAuthTitle {
            get {
                return ResourceManager.GetString("TwoFactorAuthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator code.
        /// </summary>
        public static string TwoFactorCode {
            get {
                return ResourceManager.GetString("TwoFactorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code.
        /// </summary>
        public static string TwoFactorRecoveryCode {
            get {
                return ResourceManager.GetString("TwoFactorRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA Token.
        /// </summary>
        public static string TwoFactorToken {
            get {
                return ResourceManager.GetString("TwoFactorToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is your two factor token in Boilerplate..
        /// </summary>
        public static string TwoFactorTokenSmsText {
            get {
                return ResourceManager.GetString("TwoFactorTokenSmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request lacks valid authentication credentials.
        /// </summary>
        public static string UnauthorizedException {
            get {
                return ResourceManager.GetString("UnauthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error has occurred.
        /// </summary>
        public static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown device.
        /// </summary>
        public static string UnknwonDevice {
            get {
                return ResourceManager.GetString("UnknwonDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was modified by another user after you got the original data. the operation was canceled..
        /// </summary>
        public static string UpdateConcurrencyException {
            get {
                return ResourceManager.GetString("UpdateConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update to the new version?.
        /// </summary>
        public static string UpdateToNewVersion {
            get {
                return ResourceManager.GetString("UpdateToNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a new profile image.
        /// </summary>
        public static string UploadNewProfileImage {
            get {
                return ResourceManager.GetString("UploadNewProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User image could not be found.
        /// </summary>
        public static string UserImageCouldNotBeFound {
            get {
                return ResourceManager.GetString("UserImageCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not confirmed..
        /// </summary>
        public static string UserIsNotConfirmed {
            get {
                return ResourceManager.GetString("UserIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked out. Try again in {0}.
        /// </summary>
        public static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sessions.
        /// </summary>
        public static string UserSessionsTitle {
            get {
                return ResourceManager.GetString("UserSessionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already requested the confirmation email. Try again in {0}.
        /// </summary>
        public static string WaitForEmailTokenRequestResendDelay {
            get {
                return ResourceManager.GetString("WaitForEmailTokenRequestResendDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already requested an OTP. Try again in {0}.
        /// </summary>
        public static string WaitForOtpRequestResendDelay {
            get {
                return ResourceManager.GetString("WaitForOtpRequestResendDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already requested the confirmation sms. Try again in {0}.
        /// </summary>
        public static string WaitForPhoneNumberTokenRequestResendDelay {
            get {
                return ResourceManager.GetString("WaitForPhoneNumberTokenRequestResendDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already requested the reset password token. Try again in {0}.
        /// </summary>
        public static string WaitForResetPasswordTokenRequestResendDelay {
            get {
                return ResourceManager.GetString("WaitForResetPasswordTokenRequestResendDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t revoke other sessions right now. Try again in {0}.
        /// </summary>
        public static string WaitForRevokeSessionDelay {
            get {
                return ResourceManager.GetString("WaitForRevokeSessionDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already requested the 2FA token email. Try again in {0}..
        /// </summary>
        public static string WaitForTwoFactorTokenRequestResendDelay {
            get {
                return ResourceManager.GetString("WaitForTwoFactorTokenRequestResendDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re sign in as.
        /// </summary>
        public static string YouAreSignInAs {
            get {
                return ResourceManager.GetString("YouAreSignInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to our terms..
        /// </summary>
        public static string YouHaveToAcceptTerms {
            get {
                return ResourceManager.GetString("YouHaveToAcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be signed in to continue..
        /// </summary>
        public static string YouNeedToSignIn {
            get {
                return ResourceManager.GetString("YouNeedToSignIn", resourceCulture);
            }
        }
    }
}
