// <auto-generated />
using Boilerplate.Client.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boilerplate.Client.Core.Data.Migrations;

[DbContext(typeof(AppOfflineDbContext))]
[Migration("20251201130800_Initial")]
partial class Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

        modelBuilder.Entity("Boilerplate.Shared.Dtos.Todo.TodoItemDto", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<bool>("Deleted")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsDone")
                    .HasColumnType("INTEGER");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long?>("UpdatedAt")
                    .HasColumnType("INTEGER");

                b.Property<byte[]>("Version")
                    .IsRequired()
                    .HasColumnType("BLOB");

                b.HasKey("Id");

                b.ToTable("TodoItems");
            });

        modelBuilder.Entity("CommunityToolkit.Datasync.Client.Offline.DatasyncDeltaToken", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<long>("Value")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("DatasyncDeltaTokens");
            });

        modelBuilder.Entity("CommunityToolkit.Datasync.Client.Offline.DatasyncOperation", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("EntityType")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("TEXT");

                b.Property<string>("EntityVersion")
                    .IsRequired()
                    .HasMaxLength(126)
                    .HasColumnType("TEXT");

                b.Property<int?>("HttpStatusCode")
                    .HasColumnType("INTEGER");

                b.Property<string>("Item")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ItemId")
                    .IsRequired()
                    .HasMaxLength(126)
                    .HasColumnType("TEXT");

                b.Property<int>("Kind")
                    .HasColumnType("INTEGER");

                b.Property<long?>("LastAttempt")
                    .HasColumnType("INTEGER");

                b.Property<long>("Sequence")
                    .HasColumnType("INTEGER");

                b.Property<int>("State")
                    .HasColumnType("INTEGER");

                b.Property<int>("Version")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ItemId", "EntityType");

                b.ToTable("DatasyncOperationsQueue");
            });
#pragma warning restore 612, 618
    }
}
