// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Boilerplate.Client.Core.Data
{
    public partial class AppOfflineDbContextModel
    {
        private AppOfflineDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("bbbbaa7a-81ce-4f4a-8374-cdc16b6868d5"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var todoItemDto = TodoItemDtoEntityType.Create(this);
            var datasyncDeltaToken = DatasyncDeltaTokenEntityType.Create(this);
            var datasyncOperation = DatasyncOperationEntityType.Create(this);

            TodoItemDtoEntityType.CreateAnnotations(todoItemDto);
            DatasyncDeltaTokenEntityType.CreateAnnotations(datasyncDeltaToken);
            DatasyncOperationEntityType.CreateAnnotations(datasyncOperation);

            AddAnnotation("ProductVersion", "10.0.0");
        }
    }
}
