// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Boilerplate.Client.Core.Data;

public partial class AppOfflineDbContextModel
{
    private AppOfflineDbContextModel()
        : base(skipDetectChanges: false, modelId: new Guid("0687ec37-33db-4238-976d-993653e85faf"), entityTypeCount: 1)
    {
    }

    partial void Initialize()
    {
        var userDto = UserDtoEntityType.Create(this);

        UserDtoEntityType.CreateAnnotations(userDto);

        AddAnnotation("ProductVersion", "10.0.0");
    }
}
