// <auto-generated />
using Boilerplate.Client.Core.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(OfflineDbContext), typeof(OfflineDbContextModel))]
