// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Boilerplate.Client.Core.Data
{
    public partial class OfflineDbContextModel
    {
        private OfflineDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("4b5524a2-4b87-4b64-9e87-fe2649512808"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var userDto = UserDtoEntityType.Create(this);

            UserDtoEntityType.CreateAnnotations(userDto);

            AddAnnotation("ProductVersion", "9.0.0");
        }
    }
}
