using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
#if !DEMO_SHARED_ENUM_DOCS_TESTS
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
#endif

// Compiled by RoslynCodeTaskFactory against netstandard2.0 (DemoSharedEnumDocs.targets), so no ranges,
// indices or other APIs newer than that. The test project compile-links this file with
// DEMO_SHARED_ENUM_DOCS_TESTS defined, which leaves out the MSBuild task and keeps the flattening it tests.

#if !DEMO_SHARED_ENUM_DOCS_TESTS
/// <summary>
/// Writes the prose of the shared demo enum tables (<c>DemoSharedEnums</c>) out of the library's XML
/// documentation, so the tables say exactly what IntelliSense says without anyone copying it by hand.
/// </summary>
public class GenerateDemoSharedEnumDocs : Task
{
    [Required]
    public string DocumentationFile { get; set; } = "";

    [Required]
    public ITaskItem[] Enums { get; set; } = Array.Empty<ITaskItem>();

    [Required]
    public string OutputFile { get; set; } = "";

    public override bool Execute()
    {
        if (File.Exists(DocumentationFile) is false)
        {
            Log.LogError($"The XML documentation of the library ({DocumentationFile}) is missing, so the shared demo enum tables have nothing to describe their members with.");
            return false;
        }

        var code = DemoSharedEnumDocs.Generate(XDocument.Load(DocumentationFile), Enums.Select(e => e.ItemSpec));

        if (File.Exists(OutputFile) is false || File.ReadAllText(OutputFile) != code)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(OutputFile)!);
            File.WriteAllText(OutputFile, code, new UTF8Encoding(false));
        }

        return true;
    }
}
#endif

public static class DemoSharedEnumDocs
{
    private const string Namespace = "Bit.BlazorUI.";

    /// <summary>
    /// The generated half of <c>DemoSharedEnums</c>: the summary of each enum in <paramref name="enums"/>,
    /// keyed by its name, and of each of its members, keyed by <c>Enum.Member</c>.
    /// </summary>
    public static string Generate(XDocument documentation, IEnumerable<string> enums)
    {
        var members = Members(documentation);
        var code = new StringBuilder();

        code.AppendLine("// <auto-generated>");
        code.AppendLine("// Written by DemoSharedEnumDocs.targets out of the XML documentation of Bit.BlazorUI.");
        code.AppendLine("// Edit the enum's doc comments, never this file.");
        code.AppendLine("// </auto-generated>");
        code.AppendLine();
        code.AppendLine("namespace Bit.BlazorUI.Demo.Client.Core.Models;");
        code.AppendLine();
        code.AppendLine("public static partial class DemoSharedEnums");
        code.AppendLine("{");
        code.AppendLine("    internal static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, string> Summaries = new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal)");
        code.AppendLine("    {");

        foreach (var name in enums.Distinct().OrderBy(n => n, StringComparer.Ordinal))
        {
            Append(code, name, members, "T:" + Namespace + name);

            var prefix = "F:" + Namespace + name + ".";

            foreach (var field in members.Keys.Where(k => k.StartsWith(prefix, StringComparison.Ordinal)).OrderBy(k => k, StringComparer.Ordinal))
            {
                Append(code, name + "." + field.Substring(prefix.Length), members, field);
            }
        }

        code.AppendLine("    };");
        code.AppendLine("}");

        return code.ToString();
    }

    public static Dictionary<string, XElement> Members(XDocument documentation)
    {
        var members = new Dictionary<string, XElement>(StringComparer.Ordinal);

        foreach (var member in documentation.Descendants("member"))
        {
            var name = member.Attribute("name")?.Value;

            if (name is not null)
            {
                members[name] = member;
            }
        }

        return members;
    }

    /// <summary>
    /// A summary as the plain text a table shows: every run of whitespace a single space, a link its text
    /// (a bare url is left out, since a table cell cannot follow it), and a cref the name a reader writes -
    /// <c>BitNav&lt;TItem&gt;</c>, <c>BitNav&lt;TItem&gt;.Select</c> - with the type parameters read off the
    /// type's own documentation.
    /// </summary>
    public static string Flatten(XElement summary, IReadOnlyDictionary<string, XElement> members)
    {
        return string.Join(" ", Text(summary).Split(Array.Empty<char>(), StringSplitOptions.RemoveEmptyEntries));

        string Text(XNode node)
        {
            switch (node)
            {
                case XText text:
                    return text.Value;

                case XElement { Name.LocalName: "see" or "seealso" } see:
                    var inner = string.Concat(see.Nodes().Select(Text));

                    if (inner.Trim().Length > 0) return inner;

                    var cref = see.Attribute("cref")?.Value;

                    return see.Attribute("langword")?.Value
                           ?? (cref is null ? "" : CrefName(cref, members));

                case XElement { Name.LocalName: "paramref" or "typeparamref" } reference:
                    return reference.Attribute("name")?.Value ?? "";

                case XElement { Name.LocalName: "para" or "br" } block:
                    return " " + string.Concat(block.Nodes().Select(Text)) + " ";

                case XElement element:
                    return string.Concat(element.Nodes().Select(Text));

                default:
                    return "";
            }
        }
    }

    // T:Bit.BlazorUI.BitNav`1 -> BitNav<TItem>; M:Bit.BlazorUI.BitNav`1.Select(System.String) -> BitNav<TItem>.Select;
    // M:Bit.BlazorUI.BitNav`1.#ctor -> BitNav<TItem>.
    private static string CrefName(string cref, IReadOnlyDictionary<string, XElement> members)
    {
        var kind = cref.Length > 1 && cref[1] == ':' ? cref[0] : 'T';
        var path = cref.Length > 1 && cref[1] == ':' ? cref.Substring(2) : cref;

        var parameters = path.IndexOf('(');
        if (parameters >= 0) path = path.Substring(0, parameters);

        if (kind == 'T') return TypeName(path, members);

        var dot = path.LastIndexOf('.');
        if (dot < 0) return path;

        var type = TypeName(path.Substring(0, dot), members);
        var member = path.Substring(dot + 1);

        var arity = member.IndexOf('`');
        if (arity >= 0) member = member.Substring(0, arity);

        return member == "#ctor" ? type : type + "." + member;
    }

    private static string TypeName(string fullName, IReadOnlyDictionary<string, XElement> members)
    {
        var name = fullName.Substring(fullName.LastIndexOf('.') + 1);
        var tick = name.IndexOf('`');

        if (tick < 0) return name;

        var arity = int.Parse(name.Substring(tick + 1));
        var typeParameters = members.TryGetValue("T:" + fullName, out var type)
            ? type.Elements("typeparam").Select(p => p.Attribute("name")?.Value ?? "").ToArray()
            : Array.Empty<string>();

        if (typeParameters.Length != arity)
        {
            typeParameters = arity == 1 ? new[] { "T" } : Enumerable.Range(1, arity).Select(i => "T" + i).ToArray();
        }

        return name.Substring(0, tick) + "<" + string.Join(", ", typeParameters) + ">";
    }

    private static void Append(StringBuilder code, string key, IReadOnlyDictionary<string, XElement> members, string member)
    {
        if (members.TryGetValue(member, out var element) is false) return;

        var summary = element.Element("summary");

        if (summary is null) return;

        code.Append("        [").Append(Literal(key)).Append("] = ").Append(Literal(Flatten(summary, members))).AppendLine(",");
    }

    private static string Literal(string value)
        => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
