namespace Bit.Client.Web.BlazorUI
{
    public enum BitPersonaInitialsColor
    {
        LightBlue,
        Blue,
        DarkBlue,
        Teal,
        LightGreen,
        Green,
        DarkGreen,
        LightPink,
        Pink,
        Magenta,
        Purple,
        Black,
        Orange,
        Red,
        DarkRed,
        Transparent,
        Violet,
        LightRed,
        Gold,
        Burgundy,
        WarmGray,
        CoolGray,
        Gray,
        Cyan,
        Rust,
    }
}
