// <auto-generated>
// GENERATED by Bit.BlazorUI.Assets/Scripts/generate-flags.py, together with the flag images of
// Bit.BlazorUI.Assets/wwwroot/flags. Regenerate with that script, never by hand.
// </auto-generated>

#nullable enable

namespace Bit.BlazorUI;

public partial class BitFlag
{
    /// <summary>
    /// The pixel sizes every image set of the Bit.BlazorUI.Assets package draws each flag at, smallest first.
    /// </summary>
    private static readonly int[] FlagImageSizes = [16, 24, 32, 48, 64];

    /// <summary>
    /// The box a flag image draws its flag in, in the pixels of that image.
    /// </summary>
    /// <remarks>
    /// Every image is square, with the flag drawn in its own proportions and transparent space around it.
    /// The box is the bounds of the pixels that are at least half opaque, so the faint edge the artwork
    /// antialiases a flag with stays outside it. Nearly every flag of a set shares one box per size, and the
    /// few drawn in other proportions carry their own. The boxes of one flag are not a scaling of each
    /// other - the small sizes are snapped to whole pixels - which is why every size has its own. The
    /// packaged image of the Extras package is the 16 pixel image of the flat set.
    /// </remarks>
    private static FlagBox GetFlagContentBox(BitFlagImageSet set, int size, string? iso2) => (set, size, iso2) switch
    {
        (BitFlagImageSet.Flat, 16, "CH") => new(2, 2, 12, 12),
        (BitFlagImageSet.Flat, 16, "NP") => new(3, 1, 10, 13),
        (BitFlagImageSet.Flat, 16, "RE") => new(0, 3, 16, 10),
        (BitFlagImageSet.Flat, 16, "VA") => new(2, 2, 12, 12),
        (BitFlagImageSet.Flat, 16, _) => new(1, 2, 14, 11),
        (BitFlagImageSet.Flat, 24, "CH") => new(4, 4, 16, 16),
        (BitFlagImageSet.Flat, 24, "NP") => new(4, 2, 16, 20),
        (BitFlagImageSet.Flat, 24, "VA") => new(4, 4, 16, 16),
        (BitFlagImageSet.Flat, 24, _) => new(1, 4, 22, 16),
        (BitFlagImageSet.Flat, 32, "CH") => new(6, 6, 20, 20),
        (BitFlagImageSet.Flat, 32, "NP") => new(5, 2, 22, 27),
        (BitFlagImageSet.Flat, 32, "VA") => new(6, 6, 20, 20),
        (BitFlagImageSet.Flat, 32, _) => new(1, 6, 30, 20),
        (BitFlagImageSet.Flat, 48, "CH") => new(8, 8, 32, 32),
        (BitFlagImageSet.Flat, 48, "NP") => new(8, 3, 32, 40),
        (BitFlagImageSet.Flat, 48, "RE") => new(2, 9, 44, 30),
        (BitFlagImageSet.Flat, 48, "VA") => new(8, 8, 32, 32),
        (BitFlagImageSet.Flat, 48, _) => new(1, 8, 46, 32),
        (BitFlagImageSet.Flat, 64, "CH") => new(12, 12, 40, 40),
        (BitFlagImageSet.Flat, 64, "NP") => new(10, 5, 43, 54),
        (BitFlagImageSet.Flat, 64, "VA") => new(12, 12, 40, 40),
        (BitFlagImageSet.Flat, 64, _) => new(2, 12, 60, 40),
        (BitFlagImageSet.Shiny, 16, "CH") => new(2, 2, 12, 12),
        (BitFlagImageSet.Shiny, 16, "NP") => new(3, 1, 11, 13),
        (BitFlagImageSet.Shiny, 16, "RE") => new(0, 3, 16, 10),
        (BitFlagImageSet.Shiny, 16, "VA") => new(2, 2, 12, 12),
        (BitFlagImageSet.Shiny, 16, _) => new(1, 2, 14, 11),
        (BitFlagImageSet.Shiny, 24, "CH") => new(4, 4, 16, 16),
        (BitFlagImageSet.Shiny, 24, "NP") => new(4, 2, 17, 20),
        (BitFlagImageSet.Shiny, 24, "VA") => new(4, 4, 16, 16),
        (BitFlagImageSet.Shiny, 24, _) => new(1, 4, 22, 16),
        (BitFlagImageSet.Shiny, 32, "CH") => new(6, 6, 20, 20),
        (BitFlagImageSet.Shiny, 32, "NP") => new(5, 2, 23, 27),
        (BitFlagImageSet.Shiny, 32, "VA") => new(6, 6, 20, 20),
        (BitFlagImageSet.Shiny, 32, _) => new(1, 6, 30, 20),
        (BitFlagImageSet.Shiny, 48, "CH") => new(8, 8, 32, 32),
        (BitFlagImageSet.Shiny, 48, "NP") => new(8, 3, 33, 40),
        (BitFlagImageSet.Shiny, 48, "RE") => new(1, 9, 46, 31),
        (BitFlagImageSet.Shiny, 48, "VA") => new(8, 8, 32, 32),
        (BitFlagImageSet.Shiny, 48, _) => new(1, 8, 46, 32),
        (BitFlagImageSet.Shiny, 64, "CH") => new(12, 12, 40, 40),
        (BitFlagImageSet.Shiny, 64, "NP") => new(10, 5, 43, 54),
        (BitFlagImageSet.Shiny, 64, "VA") => new(12, 12, 40, 40),
        (BitFlagImageSet.Shiny, 64, _) => new(2, 12, 60, 40),
        _ => new(0, 0, size, size),
    };
}
