//-:cnd:noEmit
// Conditional processing is off for this whole file, and the marker above has to stay on the very first line.
// This file quotes the template's own markdown conditional syntax in its doc comments and matches it with
// regexes; with processing on, the engine would read those quotes as real directives.

using System.Text.RegularExpressions;

namespace Boilerplate.Tests.Features.Documentation;

/// <summary>
/// Nothing in this repository checks a documentation claim against the tree, which is why the same class of defect
/// keeps coming back: a folder is renamed, a namespace moves, a class is renamed, and twenty-six numbered guides
/// plus <c>README.md</c> plus <c>AGENTS.md</c> keep pointing at where things used to be. All of it compiles, all of
/// it builds, and every one of those documents ships verbatim into every generated customer project - only
/// <c>.docs/25</c> is ever excluded.
/// <para>
/// Two failure shapes matter, and they are not the same size:
/// </para>
/// <list type="number">
/// <item><b>A dead link.</b> Annoying. The reader clicks and lands on nothing.</item>
/// <item><b>A snippet that has drifted away from the code it claims to quote.</b> Dangerous. A guide that
/// introduces a code block with "let's look at a real controller from the project" is asking the reader not to
/// cross-check, and the reader obliges. One such snippet had dropped the per-user ownership predicate from an
/// <c>Update</c>/<c>Delete</c> pair.</item>
/// </list>
/// <para>
/// This runs against the template's own working copy. A generated project has no <c>.template.config</c>
/// directory, and its documentation has been pruned to its own configuration, so there the test reports
/// inconclusive rather than failing.
/// </para>
/// </summary>
[TestClass, TestCategory("UnitTest")]
public class DocumentationTruthTests
{
    /// <summary>
    /// The documents that ship to the user and are therefore worth holding to this standard. Everything under
    /// <c>.docs/</c>, the auto-opened <c>README.md</c>, the instruction files an AI agent reads before touching
    /// anything, and the two READMEs that sit next to shipped configuration.
    /// </summary>
    private static readonly string[] documentationGlobs =
    [
        ".docs/*.md",
        "README.md",
        "AGENTS.md",
        "CLAUDE.md",
        "GEMINI.md",
        ".grafana/README.md",
        ".github/copilot-instructions.md",
        ".github/agents/*.md",
        ".agents/skills/*/SKILL.md",
        ".claude/skills/*/SKILL.md",
    ];

    /// <summary>
    /// Only two constructs are treated as a path reference: a markdown link destination (<c>](...)</c>) and a
    /// backticked span. Bare prose is deliberately NOT scanned - a sentence like "run it in the src/Tests
    /// directory" would otherwise be read as a path called <c>src/Tests directory</c>, and filenames in this repo
    /// legitimately contain spaces (<c>.docs/24- WebAuthn and Passwordless Authentication (Advanced).md</c>), so
    /// there is no character class that separates the two.
    /// </summary>
    /// <remarks>
    /// The inner alternation is what makes <c>[Stage 24](/.docs/24-%20...%20(Advanced).md)</c> work. CommonMark
    /// allows balanced parentheses in an unbracketed destination, and one of this repository's own filenames uses
    /// them - so a naive <c>[^)]*</c> stops at <c>(Advanced</c> and reports a working link as broken.
    /// </remarks>
    private static readonly Regex linkDestination = new(
        @"]\((?<candidate>[^()\r\n]*(?:\([^()\r\n]*\)[^()\r\n]*)*)\)", RegexOptions.Compiled);

    private static readonly Regex backtickedSpan = new(@"`(?<candidate>[^`\r\n]+)`", RegexOptions.Compiled);

    /// <summary>The top-level directories a repository-relative path can start with.</summary>
    private static readonly string[] repositoryRoots =
        ["src/", ".docs/", ".github/", ".vscode/", ".grafana/", ".azure-devops/", ".template.config/",
         ".agents/", ".claude/", ".gemini/", ".cursor/", ".junie/"];

    /// <summary>
    /// Paths that are correctly absent, each for a reason that is not "the documentation is stale". Keep this list
    /// short and keep the reasons in it - an allow-list without reasons becomes the place stale links hide.
    /// </summary>
    private static readonly Dictionary<string, string> pathsThatAreDeliberatelyAbsent = new(StringComparer.OrdinalIgnoreCase)
    {
        // template.json excludes `src/Server/**/Data/Migrations/**`: migrations are the developer's to generate
        // after instantiation, which is exactly what the docs that name this path are telling them to do.
        ["src/Server/Boilerplate.Server.Api/Infrastructure/Data/Migrations"] = "generated by the developer; excluded by template.json",

        // Firebase's own file, downloaded from the Firebase console by whoever enables push notifications.
        ["src/Client/Boilerplate.Client.Maui/Platforms/Android/google-services.json"] = "supplied by the user from the Firebase console",

        // The worked example in the DI guide walks the reader through creating this file.
        ["src/Client/Boilerplate.Client.Core/Infrastructure/Services/FeedbackService.cs"] = "the reader is told to create it; it is the guide's worked example",

        // Created by the test runner on the first `dotnet test`; template.json excludes `**/[Tt]est[Rr]esults/**`.
        ["src/Tests/TestResults"] = "created by the test runner; excluded by template.json",
        ["src/Tests/TestResults/Videos"] = "created by the test runner; excluded by template.json",
    };

    /// <summary>
    /// Every repository path a shipped document points at has to exist. This is the cheap half of the problem and
    /// it is the half that recurs: a single folder rename in <c>src/</c> invalidates a dozen links at once and
    /// nothing anywhere notices.
    /// </summary>
    [TestMethod]
    public void EveryRepositoryPathNamedInDocumentation_Should_ExistOnDisk()
    {
        var templateRoot = FindTemplateRoot();

        List<string> offenders = [];

        foreach (var (file, relativeFile) in EnumerateDocumentation(templateRoot))
        {
            var lines = File.ReadAllLines(file);

            for (var i = 0; i < lines.Length; i++)
            {
                var candidates = linkDestination.Matches(lines[i]).Select(match => match.Groups["candidate"].Value)
                    .Concat(backtickedSpan.Matches(lines[i]).Select(match => match.Groups["candidate"].Value));

                foreach (var candidate in candidates)
                {
                    if (TryNormalize(candidate, out var path) is false)
                        continue;

                    if (pathsThatAreDeliberatelyAbsent.ContainsKey(path))
                        continue;

                    var full = Path.Combine(templateRoot, path.Replace('/', Path.DirectorySeparatorChar));

                    if (File.Exists(full) || Directory.Exists(full))
                        continue;

                    offenders.Add($"{relativeFile}:{i + 1}: {path}");
                }
            }
        }

        Assert.IsEmpty(offenders,
            $"""
             These documents point at paths that do not exist. Every one of them ships into every generated
             project. Fix the path, or - if the file is genuinely the reader's to create, or is removed by
             template.json - add it to `pathsThatAreDeliberatelyAbsent` WITH the reason:
             {string.Join(Environment.NewLine, offenders)}
             """);
    }

    /// <summary>
    /// Namespaces and route shapes that a document has no business containing, because the code moved away from
    /// them and a reader who copies one gets code that does not compile or an endpoint that cannot be reached.
    /// <para>
    /// This is the half a link check cannot catch. A snippet is not a link: it renders fine, it looks
    /// authoritative, and the only way to know it is wrong is to hold it against the tree.
    /// </para>
    /// </summary>
    private static readonly (string Retired, string Replacement)[] retiredSnippetShapes =
    [
        ("Boilerplate.Shared.Dtos.", "Boilerplate.Shared.Features.* - DTOs moved under Features/ per feature"),
        ("Boilerplate.Shared.Exceptions", "Boilerplate.Shared.Infrastructure.Exceptions"),
        ("Boilerplate.Server.Api.Controllers", "Boilerplate.Server.Api.Infrastructure.Controllers"),
        ("Boilerplate.Client.Core/Services/", "Boilerplate.Client.Core/Infrastructure/Services/"),
        ("Boilerplate.Client.Core/Extensions/", "Boilerplate.Client.Core/Infrastructure/Extensions/"),
        ("src/Shared/Extensions/", "src/Shared/Infrastructure/Extensions/"),
        ("src/Shared/Controllers/", "src/Shared/Features/"),
        ("Server/Mappers/README.md", "src/Server/Boilerplate.Server.Api/Features/Mappers.md"),
        // NOT listed here, deliberately: the unversioned `Route("api/[controller]/[action]")` shape the guides
        // teach. Every controller the template ships is versioned, but `AddApiVersioning` now sets
        // `AssumeDefaultVersionWhenUnspecified` with a default of 1.0, so a controller written the way the guides
        // show it resolves to v1 instead of being rejected by the version matcher. The guides are the simpler
        // shape on purpose; the code was changed to meet them rather than the other way round.
    ];

    /// <summary>
    /// No shipped document may contain a namespace, folder or route shape the code has moved away from. Unlike the
    /// link check, this one guards the snippets - the part a reader copies into their own project.
    /// </summary>
    [TestMethod]
    public void NoDocumentationSnippet_Should_UseARetiredNamespaceOrRouteShape()
    {
        var templateRoot = FindTemplateRoot();

        List<string> offenders = [];

        foreach (var (file, relativeFile) in EnumerateDocumentation(templateRoot))
        {
            var lines = File.ReadAllLines(file);

            for (var i = 0; i < lines.Length; i++)
            {
                foreach (var (retired, replacement) in retiredSnippetShapes)
                {
                    if (lines[i].Contains(retired, StringComparison.Ordinal) is false)
                        continue;

                    offenders.Add($"{relativeFile}:{i + 1}: `{retired}` -> use {replacement}");
                }
            }
        }

        Assert.IsEmpty(offenders,
            $"""
             These documents still show a shape the code has moved away from. A reader who copies one of these
             gets a type in a namespace nothing imports, or an endpoint the API version matcher rejects:
             {string.Join(Environment.NewLine, offenders)}
             """);
    }

    /// <summary>
    /// BP-698, open. With <c>--api Standalone</c>, <c>Boilerplate.Server.Web</c> does not reference
    /// <c>Boilerplate.Server.Api</c>, so <c>Server.Api/wwwroot/images/icon.png</c> never joins Server.Web's static
    /// web assets - yet all six transactional e-mail templates resolve the logo as
    /// <c>new Uri(HttpContext.Request.GetWebAppUrl(), "images/icon.png")</c>, i.e. against the web app's origin.
    /// Every identity e-mail renders a broken image under that one parameter value.
    /// <para>
    /// <b>The obvious fix does not work, and this is the record of why.</b> Placing a copy at
    /// <c>src/Client/Boilerplate.Client.Web/wwwroot/images/icon.png</c> makes the default <c>api=Integrated</c>
    /// build fail outright: <c>Server.Api/wwwroot</c> IS contributed to Server.Web's static web assets when the
    /// project reference is present, so the second copy is a duplicate and the SDK raises
    /// <c>error : Conflicting assets with the same target path 'images/icon.png'</c>. Switching the templates to
    /// <c>GetBaseUrl()</c> is worse: <c>GetWebAppUrl()</c> exists to validate the caller-supplied origin against
    /// <c>settings.IsTrustedOrigin</c>, and <c>IdentityEmailDeliveryTests</c> asserts that
    /// <c>https://evil.example</c> is rejected there.
    /// </para>
    /// <para>
    /// <b>What would unblock this:</b> a decision on how the asset should be scoped. Either a template.json
    /// exclusion of the Client.Web copy under <c>(api == "Integrated")</c> paired with a
    /// <c>Content Remove</c> in <c>Boilerplate.Client.Web.csproj</c> so the template's own tree still builds, or a
    /// configured absolute URL for the API's own origin that the e-mail templates can use without trusting the
    /// Host header. Un-ignore this test once one of those exists.
    /// </para>
    /// </summary>
    [TestMethod, Ignore("BP-698 open: see the doc comment. The naive fix breaks the default api=Integrated build with a duplicate static-web-asset target path.")]
    public void EmailLogo_Should_ResolveAgainstAnOriginThatServesItInEveryApiMode()
    {
        var templateRoot = FindTemplateRoot();

        var webAppRelativeLogo = Path.Combine(templateRoot,
            "src", "Client", "Boilerplate.Client.Web", "wwwroot", "images", "icon.png");

        Assert.IsTrue(File.Exists(webAppRelativeLogo),
            "The e-mail templates resolve `images/icon.png` against GetWebAppUrl(), so the asset has to be "
            + "reachable from the web app's own wwwroot when api=Standalone splits the two deployments.");
    }

    /// <summary>
    /// Turns a link destination or backticked span into a repository-relative path, or rejects it. Rejected:
    /// anything that is not rooted in one of this repository's top-level directories, external URLs (a GitHub
    /// tree URL ends in a path that looks exactly like a local one), scaffolding placeholders, and build output.
    /// </summary>
    private static bool TryNormalize(string candidate, out string path)
    {
        path = string.Empty;

        candidate = candidate.Trim();

        // A GitHub URL's tail (".../tree/develop/src/ResxTranslator") is a path shape but not a local path.
        if (candidate.Contains("://", StringComparison.Ordinal))
            return false;

        // `{FeatureName}`, `[Feature]`, `<name>` and `*.razor` are placeholders in the guides and skills.
        if (candidate.Contains('{') || candidate.Contains('[') || candidate.Contains('*') || candidate.Contains('<'))
            return false;

        // A link destination may carry an anchor or a title.
        var cut = candidate.IndexOfAny([' ', '#']);
        if (cut >= 0)
            candidate = candidate[..cut];

        candidate = Uri.UnescapeDataString(candidate).Replace('\\', '/').TrimStart('/').TrimEnd('/');

        if (repositoryRoots.Any(root => candidate.StartsWith(root, StringComparison.Ordinal)) is false)
            return false;

        // Build output. `.docs/17` legitimately tells the reader to run `src/Tests/bin/Debug/net10.0/playwright.ps1`,
        // which only exists after a build.
        if (candidate.Contains("/bin/", StringComparison.Ordinal) || candidate.Contains("/obj/", StringComparison.Ordinal))
            return false;

        path = candidate;
        return true;
    }

    private static IEnumerable<(string File, string RelativeFile)> EnumerateDocumentation(string templateRoot)
    {
        foreach (var glob in documentationGlobs)
        {
            var directory = Path.GetDirectoryName(glob.Replace('/', Path.DirectorySeparatorChar)) ?? string.Empty;
            var pattern = Path.GetFileName(glob);

            // A `*` directory segment (`.agents/skills/*/SKILL.md`) fans out over the matching subdirectories,
            // so a skill added tomorrow is held to this standard without anyone editing the glob list.
            var searchRoots = directory.Contains('*')
                ? ExpandWildcardDirectory(templateRoot, directory)
                : [Path.Combine(templateRoot, directory)];

            foreach (var searchRoot in searchRoots)
            {
                if (Directory.Exists(searchRoot) is false)
                    continue;

                foreach (var file in Directory.EnumerateFiles(searchRoot, pattern, SearchOption.TopDirectoryOnly))
                {
                    yield return (file, Path.GetRelativePath(templateRoot, file).Replace(Path.DirectorySeparatorChar, '/'));
                }
            }
        }
    }

    private static IEnumerable<string> ExpandWildcardDirectory(string templateRoot, string directory)
    {
        IEnumerable<string> roots = [templateRoot];

        foreach (var segment in directory.Split(Path.DirectorySeparatorChar))
        {
            roots = segment == "*"
                ? roots.SelectMany(root => Directory.Exists(root) ? Directory.EnumerateDirectories(root) : [])
                : roots.Select(root => Path.Combine(root, segment));
        }

        return roots;
    }

    /// <summary>
    /// Walks up from the test binaries to the template's own root. A generated project has no
    /// <c>.template.config</c>, and its documentation has already been pruned to its configuration, so there this
    /// suite has nothing meaningful to assert.
    /// </summary>
    private static string FindTemplateRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null && File.Exists(Path.Combine(directory.FullName, ".template.config", "template.json")) is false)
        {
            directory = directory.Parent;
        }

        if (directory is null)
        {
            Assert.Inconclusive("No .template.config/template.json above the test binaries - this is a generated project, not the template's own tree.");
            return default!;
        }

        return directory.FullName;
    }
}
