// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Bit.Besql.Demo.Client.Data.CompiledModel
{
    public partial class OfflineDbContextModel
    {
        private OfflineDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("83924357-cac0-4352-b1b4-39edcbc1a1e3"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var weatherForecast = WeatherForecastEntityType.Create(this);

            WeatherForecastEntityType.CreateAnnotations(weatherForecast);

            AddAnnotation("ProductVersion", "9.0.0");
        }
    }
}
