// <auto-generated />
using Bit.Besql.Demo.Client.Data;
using Bit.Besql.Demo.Client.Data.CompiledModel;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(OfflineDbContext), typeof(OfflineDbContextModel))]
