namespace Boilerplate.Client.Core.Components.Pages;


public record GitHubStats(
    [property: JsonPropertyName("id")] int Id,
    [property: JsonPropertyName("node_id")] string NodeId,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("full_name")] string FullName,
    [property: JsonPropertyName("private")] bool Private,
    [property: JsonPropertyName("owner")] Owner Owner,
    [property: JsonPropertyName("html_url")] string HtmlUrl,
    [property: JsonPropertyName("description")] string Description,
    [property: JsonPropertyName("fork")] bool Fork,
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("forks_url")] string ForksUrl,
    [property: JsonPropertyName("keys_url")] string KeysUrl,
    [property: JsonPropertyName("collaborators_url")] string CollaboratorsUrl,
    [property: JsonPropertyName("teams_url")] string TeamsUrl,
    [property: JsonPropertyName("hooks_url")] string HooksUrl,
    [property: JsonPropertyName("issue_events_url")] string IssueEventsUrl,
    [property: JsonPropertyName("events_url")] string EventsUrl,
    [property: JsonPropertyName("assignees_url")] string AssigneesUrl,
    [property: JsonPropertyName("branches_url")] string BranchesUrl,
    [property: JsonPropertyName("tags_url")] string TagsUrl,
    [property: JsonPropertyName("blobs_url")] string BlobsUrl,
    [property: JsonPropertyName("git_tags_url")] string GitTagsUrl,
    [property: JsonPropertyName("git_refs_url")] string GitRefsUrl,
    [property: JsonPropertyName("trees_url")] string TreesUrl,
    [property: JsonPropertyName("statuses_url")] string StatusesUrl,
    [property: JsonPropertyName("languages_url")] string LanguagesUrl,
    [property: JsonPropertyName("stargazers_url")] string StargazersUrl,
    [property: JsonPropertyName("contributors_url")] string ContributorsUrl,
    [property: JsonPropertyName("subscribers_url")] string SubscribersUrl,
    [property: JsonPropertyName("subscription_url")] string SubscriptionUrl,
    [property: JsonPropertyName("commits_url")] string CommitsUrl,
    [property: JsonPropertyName("git_commits_url")] string GitCommitsUrl,
    [property: JsonPropertyName("comments_url")] string CommentsUrl,
    [property: JsonPropertyName("issue_comment_url")] string IssueCommentUrl,
    [property: JsonPropertyName("contents_url")] string ContentsUrl,
    [property: JsonPropertyName("compare_url")] string CompareUrl,
    [property: JsonPropertyName("merges_url")] string MergesUrl,
    [property: JsonPropertyName("archive_url")] string ArchiveUrl,
    [property: JsonPropertyName("downloads_url")] string DownloadsUrl,
    [property: JsonPropertyName("issues_url")] string IssuesUrl,
    [property: JsonPropertyName("pulls_url")] string PullsUrl,
    [property: JsonPropertyName("milestones_url")] string MilestonesUrl,
    [property: JsonPropertyName("notifications_url")] string NotificationsUrl,
    [property: JsonPropertyName("labels_url")] string LabelsUrl,
    [property: JsonPropertyName("releases_url")] string ReleasesUrl,
    [property: JsonPropertyName("deployments_url")] string DeploymentsUrl,
    [property: JsonPropertyName("created_at")] DateTime CreatedAt,
    [property: JsonPropertyName("updated_at")] DateTime UpdatedAt,
    [property: JsonPropertyName("pushed_at")] DateTime PushedAt,
    [property: JsonPropertyName("git_url")] string GitUrl,
    [property: JsonPropertyName("ssh_url")] string SshUrl,
    [property: JsonPropertyName("clone_url")] string CloneUrl,
    [property: JsonPropertyName("svn_url")] string SvnUrl,
    [property: JsonPropertyName("homepage")] string Homepage,
    [property: JsonPropertyName("size")] int Size,
    [property: JsonPropertyName("stargazers_count")] int StargazersCount,
    [property: JsonPropertyName("watchers_count")] int WatchersCount,
    [property: JsonPropertyName("language")] string Language,
    [property: JsonPropertyName("has_issues")] bool HasIssues,
    [property: JsonPropertyName("has_projects")] bool HasProjects,
    [property: JsonPropertyName("has_downloads")] bool HasDownloads,
    [property: JsonPropertyName("has_wiki")] bool HasWiki,
    [property: JsonPropertyName("has_pages")] bool HasPages,
    [property: JsonPropertyName("has_discussions")] bool HasDiscussions,
    [property: JsonPropertyName("forks_count")] int ForksCount,
    [property: JsonPropertyName("mirror_url")] object MirrorUrl,
    [property: JsonPropertyName("archived")] bool Archived,
    [property: JsonPropertyName("disabled")] bool Disabled,
    [property: JsonPropertyName("open_issues_count")] int OpenIssuesCount,
    [property: JsonPropertyName("license")] License License,
    [property: JsonPropertyName("allow_forking")] bool AllowForking,
    [property: JsonPropertyName("is_template")] bool IsTemplate,
    [property: JsonPropertyName("web_commit_signoff_required")] bool WebCommitSignoffRequired,
    [property: JsonPropertyName("topics")] IReadOnlyList<string> Topics,
    [property: JsonPropertyName("visibility")] string Visibility,
    [property: JsonPropertyName("forks")] int Forks,
    [property: JsonPropertyName("open_issues")] int OpenIssues,
    [property: JsonPropertyName("watchers")] int Watchers,
    [property: JsonPropertyName("default_branch")] string DefaultBranch,
    [property: JsonPropertyName("temp_clone_token")] object TempCloneToken,
    [property: JsonPropertyName("custom_properties")] CustomProperties CustomProperties,
    [property: JsonPropertyName("organization")] Organization Organization,
    [property: JsonPropertyName("network_count")] int NetworkCount,
    [property: JsonPropertyName("subscribers_count")] int SubscribersCount
);

public record CustomProperties(

);

public record License(
    [property: JsonPropertyName("key")] string Key,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("spdx_id")] string SpdxId,
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("node_id")] string NodeId
);

public record Organization(
    [property: JsonPropertyName("login")] string Login,
    [property: JsonPropertyName("id")] int Id,
    [property: JsonPropertyName("node_id")] string NodeId,
    [property: JsonPropertyName("avatar_url")] string AvatarUrl,
    [property: JsonPropertyName("gravatar_id")] string GravatarId,
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("html_url")] string HtmlUrl,
    [property: JsonPropertyName("followers_url")] string FollowersUrl,
    [property: JsonPropertyName("following_url")] string FollowingUrl,
    [property: JsonPropertyName("gists_url")] string GistsUrl,
    [property: JsonPropertyName("starred_url")] string StarredUrl,
    [property: JsonPropertyName("subscriptions_url")] string SubscriptionsUrl,
    [property: JsonPropertyName("organizations_url")] string OrganizationsUrl,
    [property: JsonPropertyName("repos_url")] string ReposUrl,
    [property: JsonPropertyName("events_url")] string EventsUrl,
    [property: JsonPropertyName("received_events_url")] string ReceivedEventsUrl,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("user_view_type")] string UserViewType,
    [property: JsonPropertyName("site_admin")] bool SiteAdmin
);

public record Owner(
    [property: JsonPropertyName("login")] string Login,
    [property: JsonPropertyName("id")] int Id,
    [property: JsonPropertyName("node_id")] string NodeId,
    [property: JsonPropertyName("avatar_url")] string AvatarUrl,
    [property: JsonPropertyName("gravatar_id")] string GravatarId,
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("html_url")] string HtmlUrl,
    [property: JsonPropertyName("followers_url")] string FollowersUrl,
    [property: JsonPropertyName("following_url")] string FollowingUrl,
    [property: JsonPropertyName("gists_url")] string GistsUrl,
    [property: JsonPropertyName("starred_url")] string StarredUrl,
    [property: JsonPropertyName("subscriptions_url")] string SubscriptionsUrl,
    [property: JsonPropertyName("organizations_url")] string OrganizationsUrl,
    [property: JsonPropertyName("repos_url")] string ReposUrl,
    [property: JsonPropertyName("events_url")] string EventsUrl,
    [property: JsonPropertyName("received_events_url")] string ReceivedEventsUrl,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("user_view_type")] string UserViewType,
    [property: JsonPropertyName("site_admin")] bool SiteAdmin
);


