<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <EnableMSTestRunner>true</EnableMSTestRunner>
        <OutputType>Exe</OutputType>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MSTest" Version="4.5.1" />
        <PackageReference Include="Spectre.Console.Testing" Version="0.57.2" />
        <PackageReference Include="OpenTelemetry.Exporter.InMemory" Version="1.19.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Bit.Cli\Bit.Cli.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    </ItemGroup>

</Project>
