using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Bit.SourceGenerators;

[Generator]
public class BlazorSetParametersSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var parameterProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Microsoft.AspNetCore.Components.ParameterAttribute",
                predicate: static (node, _) => IsPartialClassProperty(node),
                transform: static (ctx, ct) => ExtractBitProperty(ctx, ct))
            .Where(static p => p is not null)
            .Select(static (p, _) => p!.Value);

        var cascadingProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Microsoft.AspNetCore.Components.CascadingParameterAttribute",
                predicate: static (node, _) => IsPartialClassProperty(node),
                transform: static (ctx, ct) => ExtractBitProperty(ctx, ct))
            .Where(static p => p is not null)
            .Select(static (p, _) => p!.Value);

        var combined = parameterProvider.Collect()
            .Combine(cascadingProvider.Collect())
            .Select(static (pair, _) =>
                pair.Left
                    .AddRange(pair.Right)
                    .GroupBy(static p => (p.ContainingTypeFullName, p.PropertyName))
                    .Select(static g => g.First())
                    .ToImmutableArray());

        context.RegisterSourceOutput(combined, static (spc, properties) => Execute(spc, properties));
    }

    private static bool IsPartialClassProperty(SyntaxNode node)
    {
        return node is PropertyDeclarationSyntax prop &&
               prop.Parent is (ClassDeclarationSyntax or RecordDeclarationSyntax) and TypeDeclarationSyntax typeDecl &&
               typeDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
    }

    private static BitProperty? ExtractBitProperty(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not IPropertySymbol prop) return null;

        var containingType = prop.ContainingType;
        if (containingType is null) return null;

        if (InheritsFromComponentBase(containingType) is false) return null;

        if (TypeDeclaresSetParametersAsync(containingType)) return null;

        var classNameForCode = BuildClassNameForCode(containingType);
        var isBaseTypeComponentBase = containingType.BaseType?.ToDisplayString() == "Microsoft.AspNetCore.Components.ComponentBase";

        return new BitProperty(
            ContainingTypeFullName: containingType.ToDisplayString(),
            ClassName: containingType.Name,
            ClassNameForCode: classNameForCode,
            ClassNamespace: containingType.ContainingNamespace.ToDisplayString(),
            IsBaseTypeComponentBase: isBaseTypeComponentBase,
            PropertyName: prop.Name,
            PropertyType: prop.Type.ToDisplayString());
    }

    private static void Execute(SourceProductionContext spc, ImmutableArray<BitProperty> properties)
    {
        foreach (var group in properties.GroupBy(p => p.ContainingTypeFullName))
        {
            var list = group.ToList();
            var first = list[0];
            string source = GeneratePartialClassToOverrideSetParameters(first, list);
            spc.AddSource($"{EscapeForHint(first.ContainingTypeFullName)}_SetParametersAsync.AutoGenerated.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GeneratePartialClassToOverrideSetParameters(BitProperty classInfo, List<BitProperty> properties)
    {
        var namespaceName = classInfo.ClassNamespace;
        var className = classInfo.ClassNameForCode;
        var isBase = classInfo.IsBaseTypeComponentBase;

        StringBuilder source = new StringBuilder($@"using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

namespace {namespaceName}
{{
    public partial class {className}
    {{
        [global::System.CodeDom.Compiler.GeneratedCode(""Bit.SourceGenerators"",""{BitSourceGeneratorUtil.GetPackageVersion()}"")]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public override Task SetParametersAsync(ParameterView parameters)
        {{
");
        source.AppendLine("            foreach (var parameter in parameters)");
        source.AppendLine("            {");
        source.AppendLine("                switch (parameter.Name)");
        source.AppendLine("                {");

        foreach (var bitProperty in properties)
        {
            source.AppendLine($"                    case nameof({bitProperty.PropertyName}):");
            source.AppendLine($"                       {bitProperty.PropertyName} = parameter.Value is null ? default! : ({bitProperty.PropertyType})parameter.Value;");
            source.AppendLine("                       break;");
        }

        source.AppendLine("                }");
        source.AppendLine("            }");

        if (isBase)
        {
            source.AppendLine("            return base.SetParametersAsync(ParameterView.Empty);");
        }
        else
        {
            source.AppendLine("            return base.SetParametersAsync(parameters);");
        }

        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    private static string BuildClassNameForCode(INamedTypeSymbol classSymbol)
    {
        if (classSymbol.IsGenericType)
        {
            var typeArgs = string.Join(", ", classSymbol.TypeParameters.Select(s => s.Name));
            return $"{classSymbol.Name}<{typeArgs}>";
        }
        return classSymbol.Name;
    }

    private static bool InheritsFromComponentBase(INamedTypeSymbol? typeSymbol)
    {
        if (typeSymbol is null) return false;
        
        if (typeSymbol.TypeKind is not TypeKind.Class) return false;

        var baseType = typeSymbol.BaseType;
        if (baseType is null) return false;

        if (baseType.ToDisplayString() == "Microsoft.AspNetCore.Components.ComponentBase") return true;
        
        return InheritsFromComponentBase(baseType);
    }

    private static bool TypeDeclaresSetParametersAsync(INamedTypeSymbol containingType)
    {
        foreach (var member in containingType.GetMembers())
        {
            if (member is not IMethodSymbol method) continue;
            if (method.Name != "SetParametersAsync") continue;
            if (method.Parameters.Length != 1) continue;
            
            var parameterType = method.Parameters[0].Type;
            var isParameterView = parameterType.ToDisplayString() == "Microsoft.AspNetCore.Components.ParameterView" || 
                                  parameterType.Name == "ParameterView";
            if (isParameterView is false) continue;

            var returnsTask = method.ReturnType.ToDisplayString() == "System.Threading.Tasks.Task" || 
                              method.ReturnType.Name == "Task";
            if (returnsTask is false) continue;

            return true;
        }

        return false;
    }

    private static string EscapeForHint(string fullyQualifiedName)
        => fullyQualifiedName.Replace('<', '[').Replace('>', ']').Replace(' ', '_');
}
