using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Bit.SourceGenerators;

[Generator]
public class BlazorSetParametersSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var parameterProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Microsoft.AspNetCore.Components.ParameterAttribute",
                predicate: static (node, _) => IsPartialClassProperty(node),
                transform: static (ctx, ct) => ExtractBitProperty(ctx, ct))
            .Where(static p => p is not null)
            .Select(static (p, _) => p!.Value);

        var cascadingProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Microsoft.AspNetCore.Components.CascadingParameterAttribute",
                predicate: static (node, _) => IsPartialClassProperty(node),
                transform: static (ctx, ct) => ExtractBitProperty(ctx, ct))
            .Where(static p => p is not null)
            .Select(static (p, _) => p!.Value);

        var combined = parameterProvider.Collect()
            .Combine(cascadingProvider.Collect())
            .Select(static (pair, _) =>
                pair.Left
                    .AddRange(pair.Right)
                    .GroupBy(static p => (p.ContainingTypeFullName, p.PropertyName))
                    .Select(static g => g.First())
                    .ToImmutableArray());

        context.RegisterSourceOutput(combined, static (spc, properties) => Execute(spc, properties));
    }

    private static bool IsPartialClassProperty(SyntaxNode node)
    {
        return node is PropertyDeclarationSyntax prop &&
               prop.Parent is (ClassDeclarationSyntax or RecordDeclarationSyntax) and TypeDeclarationSyntax typeDecl &&
               typeDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
    }

    private static BitProperty? ExtractBitProperty(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not IPropertySymbol prop) return null;

        var containingType = prop.ContainingType;
        if (containingType is null) return null;

        var compilation = ctx.SemanticModel.Compilation;
        var componentBaseType = compilation.GetTypeByMetadataName("Microsoft.AspNetCore.Components.ComponentBase");

        // Legacy syntax receiver did not filter by base type; omitting that preserves parity with ISyntaxContextReceiver output volume.

        // Legacy syntax receiver skipped when any member was named SetParametersAsync (method, property, etc.).
        if (ContainingTypeDeclaresSetParametersAsyncName(containingType)) return null;

        var classNameForCode = BuildClassNameForCode(containingType);
        var isBaseTypeComponentBase = containingType.BaseType is not null &&
            componentBaseType is not null &&
            SymbolEqualityComparer.Default.Equals(containingType.BaseType, componentBaseType);

        return new BitProperty(
            ContainingTypeFullName: containingType.ToDisplayString(),
            ClassName: containingType.Name,
            ClassNameForCode: classNameForCode,
            ClassNamespace: containingType.ContainingNamespace.ToDisplayString(),
            IsBaseTypeComponentBase: isBaseTypeComponentBase,
            PropertyName: prop.Name,
            PropertyType: prop.Type.ToDisplayString());
    }

    private static void Execute(SourceProductionContext spc, ImmutableArray<BitProperty> properties)
    {
        foreach (var group in properties.GroupBy(p => p.ContainingTypeFullName))
        {
            var list = group.ToList();
            var first = list[0];
            string source = GeneratePartialClassToOverrideSetParameters(first, list);
            spc.AddSource($"{EscapeForHint(first.ContainingTypeFullName)}_SetParametersAsync.AutoGenerated.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GeneratePartialClassToOverrideSetParameters(BitProperty classInfo, List<BitProperty> properties)
    {
        var namespaceName = classInfo.ClassNamespace;
        var className = classInfo.ClassNameForCode;
        var isBase = classInfo.IsBaseTypeComponentBase;

        StringBuilder source = new StringBuilder($@"using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

namespace {namespaceName}
{{
    public partial class {className}
    {{
        [global::System.CodeDom.Compiler.GeneratedCode(""Bit.SourceGenerators"",""{BitSourceGeneratorUtil.GetPackageVersion()}"")]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public override Task SetParametersAsync(ParameterView parameters)
        {{
");
        source.AppendLine("            foreach (var parameter in parameters)");
        source.AppendLine("            {");
        source.AppendLine("                switch (parameter.Name)");
        source.AppendLine("                {");

        foreach (var bitProperty in properties)
        {
            source.AppendLine($"                    case nameof({bitProperty.PropertyName}):");
            source.AppendLine($"                       {bitProperty.PropertyName} = parameter.Value is null ? default! : ({bitProperty.PropertyType})parameter.Value;");
            source.AppendLine("                       break;");
        }

        source.AppendLine("                }");
        source.AppendLine("            }");

        if (isBase)
        {
            source.AppendLine("            return base.SetParametersAsync(ParameterView.Empty);");
        }
        else
        {
            source.AppendLine("            return base.SetParametersAsync(parameters);");
        }

        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    private static string BuildClassNameForCode(INamedTypeSymbol classSymbol)
    {
        if (classSymbol.IsGenericType)
        {
            // Same as legacy GetClassName: use resolved type arguments for generic arity display.
            var typeArgs = string.Join(", ", classSymbol.TypeArguments.Select(s => s.Name));
            return $"{classSymbol.Name}<{typeArgs}>";
        }
        return classSymbol.Name;
    }

    /// <summary>
    /// Matches the legacy syntax receiver: skip if the declaring type has any member named SetParametersAsync.
    /// </summary>
    private static bool ContainingTypeDeclaresSetParametersAsyncName(INamedTypeSymbol containingType)
        => containingType.GetMembers().Any(m => m.Name == "SetParametersAsync");

    private static string EscapeForHint(string fullyQualifiedName)
        => fullyQualifiedName.Replace('<', '[').Replace('>', ']').Replace(' ', '_');
}
