namespace Boilerplate.Shared.Infrastructure.Exceptions;

/// <summary>
/// A machine-readable format for specifying errors in HTTP API responses based on <see href="https://tools.ietf.org/html/rfc7807"/>.
/// </summary>
public partial class AppProblemDetails
{
    /// <summary>
    /// A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when
    /// dereferenced, it provide human-readable documentation for the problem type
    /// (e.g., using HTML [W3C.REC-html5-20141028]). When this member is not present, its value is assumed to be
    /// "about:blank".
    /// </summary>
    [JsonPropertyOrder(-5)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence
    /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
    /// see[RFC7231], Section 3.4).
    /// </summary>
    [JsonPropertyOrder(-4)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("title")]
    public string? Title { get; set; }

    /// <summary>
    /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
    /// </summary>
    [JsonPropertyOrder(-3)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("status")]
    public int? Status { get; set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    [JsonPropertyOrder(-2)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("detail")]
    public string? Detail { get; set; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
    /// </summary>
    [JsonPropertyOrder(-1)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("instance")]
    public string? Instance { get; set; }

    /// <summary>
    /// Gets the <see cref="IDictionary{TKey, TValue}"/> for extension members.
    /// <para>
    /// Problem type definitions MAY extend the problem details object with additional members. Extension members appear in the same namespace as
    /// other members of a problem type.
    /// </para>
    /// </summary>
    /// <remarks>
    /// The round-tripping behavior for <see cref="Extensions"/> is determined by the implementation of the Input \ Output formatters.
    /// In particular, complex types or collection types may not round-trip to the original type when using the built-in JSON or XML formatters.
    /// </remarks>
    [JsonExtensionData]
    public Dictionary<string, object?> Extensions { get; set; } = new(StringComparer.Ordinal);

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Key { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ErrorResourcePayload? Payload { get; set; }


    /// <remarks>
    /// This runs inside the client's own error handling, so it must not throw: a body that reaches it without a
    /// resolvable <see cref="Type"/>, without a <see cref="Key"/>, or naming a type this cannot construct has to
    /// degrade into an <see cref="UnknownException"/> rather than replace the real failure with a
    /// <c>MissingMethodException</c> in the user's face.
    /// </remarks>
    public static implicit operator Exception(AppProblemDetails problemDetails)
    {
        var title = problemDetails.Title ?? nameof(UnknownException);
        var key = problemDetails.Key ?? nameof(UnknownException);

        Type exceptionType = ResolveExceptionType(problemDetails.Type) ?? typeof(UnknownException);

        Exception exp;

        if (exceptionType == typeof(ResourceValidationException))
        {
            exp = new ResourceValidationException(title, problemDetails.Payload);
        }
        else
        {
            // TransientException and the like only offer the (string) overload, so the constructor decides the
            // argument shape rather than the other way around.
            object? arg = exceptionType.GetConstructor([typeof(LocalizedString)]) is not null ? new LocalizedString(key, title) : title;

            exp = Activator.CreateInstance(exceptionType, [arg]) as Exception ?? new UnknownException(title);
        }

        // Assigned rather than left to the constructor: the (string) and the ResourceValidationException overloads
        // both set Key to the localized message, and Key is what call sites compare against a nameof(AppStrings.X).
        if (exp is KnownException knownException)
        {
            knownException.Key = key;
        }

        foreach (var data in problemDetails.Extensions)
        {
            exp.Data[data.Key] = data.Value;
        }

        return exp;
    }

    private static Type? ResolveExceptionType(string? type)
    {
        if (string.IsNullOrEmpty(type))
            return null;

        var assembly = typeof(KnownException).Assembly;

        var exceptionType = assembly.GetType(type)
            ?? assembly.ExportedTypes.FirstOrDefault(t => type.EndsWith(t.Name, StringComparison.Ordinal));

        // The fuzzy EndsWith fallback above matches any exported type name, not just exception ones.
        if (exceptionType is null || typeof(Exception).IsAssignableFrom(exceptionType) is false || exceptionType.IsAbstract)
            return null;

        if (exceptionType == typeof(ResourceValidationException))
            return exceptionType; // Built through its own constructor by the caller.

        var isConstructible = exceptionType.GetConstructor([typeof(LocalizedString)]) is not null
                           || exceptionType.GetConstructor([typeof(string)]) is not null;

        return isConstructible ? exceptionType : null;
    }
}
