name: bit platform CI - Brouter

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'src/Brouter/**'

env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true

permissions:
  contents: read

jobs:
  build-Brouter:
    if: startsWith(github.event.pull_request.title, 'Prerelease') != true && startsWith(github.event.pull_request.title, 'Release') != true && startsWith(github.event.pull_request.title, 'Version') != true
    name: build Bit.Brouter
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout source code
      uses: actions/checkout@v7
      with:
          persist-credentials: false

    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: src/global.json

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: dotnet workload restore
      run:  cd src/Brouter && dotnet workload restore

    - name: InstallNodejsDependencies
      continue-on-error: true # Error MSB4057, not all csproj files have InstallNodejsDependencies target.
      run: dotnet build src/Brouter/Bit.Brouter.slnx -t:InstallNodejsDependencies -m:1 -f net10.0

    - name: dotnet build
      run: dotnet build src/Brouter/Bit.Brouter.slnx
