name: bit platform CI - Websites

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      prerelease_packages:
        type: boolean
        default: false
  pull_request:
    paths:
    - 'src/Websites/**'
    - 'src/Minifier/**'

env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true

permissions:
  contents: read
  actions: read

jobs:
  build-Websites:
    if: startsWith(github.event.pull_request.title, 'Prerelease') != true && startsWith(github.event.pull_request.title, 'Release') != true && startsWith(github.event.pull_request.title, 'Version') != true
    name: build Bit.Websites
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
          persist-credentials: false

    - name: Setup .NET 11.0
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        global-json-file: src/global.json

    - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
      with:
        node-version: 24
      
    - name: Use prerelease packages
      if: inputs.prerelease_packages
      uses: ./.github/actions/use-prerelease-packages
      with:
        project-folder: .

    - name: Install wasm
      run: cd src && dotnet workload install wasm-tools

    - name: Build Careers
      run: dotnet build src/Websites/Careers/Bit.Websites.Careers.slnx

    - name: Build Platform
      run: dotnet build src/Websites/Platform/Bit.Websites.Platform.slnx

    - name: Build Sales
      run: dotnet build src/Websites/Sales/Bit.Websites.Sales.slnx
