name: bit platform CI - release

on:
  pull_request:
    paths:
    - 'src/**'

env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true

permissions:
  contents: read

jobs:
  build-release:
    if: startsWith(github.event.pull_request.title, 'Prerelease') || startsWith(github.event.pull_request.title, 'Release') || startsWith(github.event.pull_request.title, 'Version')
    name: build and test for release
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout source code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
          persist-credentials: false

    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        global-json-file: src/global.json

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        dotnet-version: 9.0.x

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        dotnet-version: 8.0.x

    - uses: actions/setup-node@v6
      with:
        node-version: 24
      
    - name: Install wasm and maui
      run:  cd src && dotnet workload install maui-android wasm-tools wasm-tools-net9 wasm-tools-net8

    - name: InstallNodejsDependencies
      continue-on-error: true # Error MSB4057, not all csproj files have InstallNodejsDependencies target.
      run: dotnet build src/Bit.CI.Release.slnx -t:InstallNodejsDependencies -m:1 -f net10.0

    - name: dotnet build
      run: dotnet build src/Bit.CI.Release.slnx -c Release
