name: Brouter Demo CD

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build_blazor_wasm:
    name: build blazor wasm
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout source code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
          persist-credentials: false

    - name: Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        global-json-file: src/global.json

    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24

    - name: Install wasm
      run:  cd src && dotnet workload install wasm-tools

    - name: Publish
      run: dotnet publish src/Brouter/InteralDemos/Wasm/Bit.Brouter.Demos.Wasm/Bit.Brouter.Demos.Wasm.csproj -c Release -o server -p:Version="${{ vars.APP_VERSION}}" -p:InvariantGlobalization=true

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: BrouterDemo
        path: server
        include-hidden-files: true
