name: Todo Sample CD

# Project templates come equipped with CI/CD for both Azure DevOps and GitHub, providing you with a hassle-free way to get started with your new project. It is important to note that you should not depend on the contents of this file. More info at https://bitplatform.dev/templates/dev-ops

env:
  SERVER_WEB_ADDRESS: 'https://todo.bitplatform.dev'
  SERVER_API_ADDRESS: 'https://todo-api.bitplatform.dev'
  OpenAI__ApiKey: ${{ secrets.OpenAI__ApiKey }}
  OpenAI__Endpoint: ${{ secrets.OpenAI__Endpoint }}
  OPENAI__MODEL: ${{ secrets.OPENAI__MODEL }}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build_blazor_hybrid_android:
    name: build blazor hybrid (android)
    runs-on: ubuntu-24.04
  
    steps:
     
    - name: Checkout source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
          persist-credentials: false
     
    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        global-json-file: src/global.json

    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24

    - name: Create project from Boilerplate
      run: |
        cd src/Templates/Boilerplate && dotnet build -c Release
        dotnet pack -c Release -o . -p:ReleaseVersion=0.0.0 -p:PackageVersion=0.0.0
        dotnet new install Bit.Boilerplate.0.0.0.nupkg
        cd ../../../ && dotnet new bit-bp --name TodoSample --database PostgreSQL --sample --sentry --apiServerUrl ${{ env.SERVER_API_ADDRESS }} --webAppUrl ${{ env.SERVER_WEB_ADDRESS }} --filesStorage AzureBlobStorage --notification --captcha reCaptcha --signalR --ads --multitenant false --brouter false
  
    - name: Extract Android signing key from env
      uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c # v2
      with:
          fileDir: './TodoSample/src/Client/TodoSample.Client.Maui/'
          fileName: 'TodoSample.keystore'
          encodedString: ${{ secrets.ANDROID_RELEASE_KEYSTORE_FILE_BASE64 }}

    - name: Extract Android signing key from env
      uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c # v2
      with:
          fileDir: './TodoSample/src/Client/TodoSample.Client.Maui/Platforms/Android'
          fileName: 'google-services.json'
          encodedString: ${{ secrets.TODO_GOOGLE_SERVICES_JSON_BASE64 }}
  
    - name: Use Bit.ResxTranslator
      run: |
            cd TodoSample
            dotnet tool install --global Bit.ResxTranslator --prerelease
            bit-resx-translate

    - name: Update core appsettings.json
      uses: devops-actions/variable-substitution@ae7b1f3676ae374dc70282e6b9650bc50b611222 # v1.2
      with:
        files: 'TodoSample/**/appsettings*json'
      env:
        WebAppUrl: ${{ env.SERVER_WEB_ADDRESS }}
        ServerAddress: ${{ env.SERVER_API_ADDRESS }}
        Logging.Sentry.Dsn: ${{ secrets.TODO_SENTRY_DSN }}
        GoogleRecaptchaSiteKey: ${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}

    - name: Install maui
      run: cd src && dotnet workload install maui-android

    - name: Install Android Sdk platform tools
      run: ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools"
  
    - name: Delete App Icon
      run: rm TodoSample/src/Client/TodoSample.Client.Maui/Resources/AppIcon/appicon.svg

    - name: Extract App Icon from env
      uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c # v2
      with:
          fileDir: './TodoSample/src/Client/TodoSample.Client.Maui/Resources/AppIcon/'
          fileName: 'appicon.svg'
          encodedString: ${{ vars.TODO_ICON }}

    - name: Delete App Splash Screen
      run: rm TodoSample/src/Client/TodoSample.Client.Maui/Resources/Splash/splash.svg

    - name: Extract App Splash Screen from env
      uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c # v2
      with:
          fileDir: './TodoSample/src/Client/TodoSample.Client.Maui/Resources/Splash/'
          fileName: 'splash.svg'
          encodedString: ${{ vars.TODO_SPLASH_SCREEN }}

    - name: Generate CSS/JS files
      run: |
          dotnet build TodoSample/src/Client/TodoSample.Client.Core/TodoSample.Client.Core.csproj -t:BeforeBuildTasks -p:Version="${{ vars.APP_VERSION}}" --no-restore -c Release
          dotnet build TodoSample/src/Client/TodoSample.Client.Maui/TodoSample.Client.Maui.csproj -t:BeforeBuildTasks -p:Version="${{ vars.APP_VERSION}}" --no-restore -c Release
  
    - name: Publish aab
      run: dotnet publish TodoSample/src/Client/TodoSample.Client.Maui/TodoSample.Client.Maui.csproj -c Release -p:AndroidPackageFormat=aab -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="TodoSample.keystore" -p:AndroidSigningKeyAlias=bitplatform -p:AndroidSigningKeyPass="${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.ANDROID_RELEASE_SIGNING_PASSWORD }}" -p:Version="${{ vars.APP_VERSION }}" -p:ApplicationTitle="TodoSample" -p:ApplicationId="com.bitplatform.Todo.Template" -f net10.0-android
  
    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: android-bundle
        path: TodoSample/src/Client/TodoSample.Client.Maui/bin/Release/net10.0-android/*-Signed.*
        
  build_blazor_hybrid_ios:
    name: build blazor hybrid (iOS-macOS)
    runs-on: macOS-26
  
    steps:
     
    - name: Checkout source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
          persist-credentials: false
     
    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        global-json-file: src/global.json

    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24

    - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
      with:
        xcode-version: '26.6'

    - name: Create project from Boilerplate
      run: |
        cd src/Templates/Boilerplate && dotnet build -c Release
        dotnet pack -c Release -o . -p:ReleaseVersion=0.0.0 -p:PackageVersion=0.0.0
        dotnet new install Bit.Boilerplate.0.0.0.nupkg
        cd ../../../ && dotnet new bit-bp --name TodoSample --database PostgreSQL --sample --sentry --apiServerUrl ${{ env.SERVER_API_ADDRESS }} --webAppUrl ${{ env.SERVER_WEB_ADDRESS }} --filesStorage AzureBlobStorage --notification --captcha reCaptcha --signalR --ads --multitenant false --brouter false
      
    - name: Use Bit.ResxTranslator
      run: |
            cd TodoSample
            dotnet tool install --global Bit.ResxTranslator --prerelease
            bit-resx-translate

    - name: Update core appsettings.json
      uses: devops-actions/variable-substitution@ae7b1f3676ae374dc70282e6b9650bc50b611222 # v1.2
      with:
        files: 'TodoSample/**/appsettings*json'
      env:
        WebAppUrl: ${{ env.SERVER_WEB_ADDRESS }}
        ServerAddress: ${{ env.SERVER_API_ADDRESS }}
        Logging.Sentry.Dsn: ${{ secrets.TODO_SENTRY_DSN }}
        GoogleRecaptchaSiteKey: ${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}

    - name: Install maui
      run: cd src && dotnet workload install maui

    - name: Import Code-Signing Certificates
      uses: apple-actions/import-codesign-certs@5142e029c445c10ffc7149d172e540235a065466 # v7.0.0
      with:
        p12-file-base64: ${{ secrets.APPSTORE_CODE_SIGNING_CERTIFICATE_FILE_BASE64 }}
        p12-password: ${{ secrets.APPSTORE_CODE_SIGNING_CERTIFICATE_FILE_PASSWORD }}

    - name: Download Apple Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@2126b5f86a0e2863cbf4d2d312112b22b943a594 # v6.1.0
      with:
        bundle-id: 'com.bitplatform.Todo.Template'
        issuer-id: ${{ secrets.APPSTORE_API_KEY_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_API_KEY_PRIVATE_KEY }}

    - name: Delete App Icon
      run: rm TodoSample/src/Client/TodoSample.Client.Maui/Resources/AppIcon/appicon.svg

    - name: Extract App Icon from env
      uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c # v2
      with:
          fileDir: './TodoSample/src/Client/TodoSample.Client.Maui/Resources/AppIcon/'
          fileName: 'appicon.svg'
          encodedString: ${{ vars.TODO_ICON }}

    - name: Delete App Splash Screen
      run: rm TodoSample/src/Client/TodoSample.Client.Maui/Resources/Splash/splash.svg

    - name: Extract App Splash Screen from env
      uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c # v2
      with:
          fileDir: './TodoSample/src/Client/TodoSample.Client.Maui/Resources/Splash/'
          fileName: 'splash.svg'
          encodedString: ${{ vars.TODO_SPLASH_SCREEN }}

    - name: Generate CSS/JS files
      run: |
          dotnet build TodoSample/src/Client/TodoSample.Client.Core/TodoSample.Client.Core.csproj -t:BeforeBuildTasks -p:Version="${{ vars.APP_VERSION}}" --no-restore -c Release
          dotnet build TodoSample/src/Client/TodoSample.Client.Maui/TodoSample.Client.Maui.csproj -t:BeforeBuildTasks -p:Version="${{ vars.APP_VERSION}}" --no-restore -c Release
  
    - name: Build ipa
      run: dotnet publish TodoSample/src/Client/TodoSample.Client.Maui/TodoSample.Client.Maui.csproj -p:RuntimeIdentifier=ios-arm64 -c Release -p:ArchiveOnBuild=true -p:CodesignKey="iPhone Distribution" -p:CodesignProvision="TodoTemplate" -p:Version="${{ vars.APP_VERSION }}" -p:ApplicationTitle="Todo" -p:ApplicationId="com.bitplatform.Todo.Template" -f net10.0-ios

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ios-bundle
        path: TodoSample/src/Client/TodoSample.Client.Maui/bin/release/net10.0-ios/ios-arm64/publish/*.ipa
