<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RunSettingsFilePath>$(MSBuildProjectDirectory)\.runsettings</RunSettingsFilePath>
        <TestingPlatformCommandLineArguments>--settings ./.runsettings --report-trx --report-trx-filename TestResults.trx --results-directory ./TestResults</TestingPlatformCommandLineArguments>
        <EnableMSTestRunner>true</EnableMSTestRunner>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Condition=" '$(aspire)' == 'true' OR '$(aspire)' == '' " Include="Aspire.Hosting.Testing" />
        <PackageReference Include="Bit.BlazorES2019" />
        <PackageReference Include="FakeItEasy" />
        <PackageReference Condition=" '$(advancedTests)' == 'true' OR '$(advancedTests)' == '' " Include="Microsoft.Extensions.TimeProvider.Testing" />
        <PackageReference Condition=" '$(advancedTests)' == 'true' OR '$(advancedTests)' == '' " Include="Otp.NET" />
        <PackageReference Include="Microsoft.Playwright.MSTest.v4" />
        <PackageReference Include="bunit" />
        <PackageReference Include="MSTest" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Server\Boilerplate.Server.Web\Boilerplate.Server.Web.csproj" />
        <ProjectReference Include="..\Server\Boilerplate.Server.Api\Boilerplate.Server.Api.csproj" />
        <ProjectReference Condition=" '$(aspire)' == 'true' OR '$(aspire)' == '' " Include="..\Server\Boilerplate.Server.AppHost\Boilerplate.Server.AppHost.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Net" />
        <Using Include="System.Net.Http.Headers" />
        <Using Include="System.Net.Http.Json" />
        <Using Include="System.Text.RegularExpressions" />
        <Using Include="Boilerplate.Shared" />
        <Using Include="Boilerplate.Shared.Features.Identity" />
        <Using Include="Boilerplate.Server.Web" />
        <Using Include="Boilerplate.Server.Api.Infrastructure.Data" />
        <Using Include="Boilerplate.Server.Api.Features.Identity.Models" />
        <Using Include="Boilerplate.Client.Core.Infrastructure.Services" />
        <Using Include="Boilerplate.Client.Core.Infrastructure.Services.Contracts" />
        <Using Include="Boilerplate.Tests.Infrastructure" />
        <Using Include="Boilerplate.Tests.Infrastructure.Services" />
        <Using Include="Boilerplate.Tests.Features.Identity" />
        <Using Include="Microsoft.AspNetCore.Http" />
        <Using Include="Microsoft.AspNetCore.Components" />
        <Using Include="Microsoft.EntityFrameworkCore" />
        <Using Include="Microsoft.Extensions.Hosting" />
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
        <Using Include="Microsoft.Playwright" />
        <Using Include="Microsoft.Playwright.MSTest" />
        <Using Include="FakeItEasy" />
        <Using Condition=" '$(advancedTests)' == 'true' OR '$(advancedTests)' == '' " Include="Boilerplate.Tests.Infrastructure.Components" />
    </ItemGroup>

</Project>
